### ISSUE TITLE
Search not cleared after ESC

### ISSUE THREAD

**Issue by rshmhrj** [jpanther/congo#109]
## Steps followed:
1. Upgraded to congo version 2.0
2. Ran long tailwind command to regenerate all the necessary CSS (had to install postcss from inside themes/congo first though)
3. Started server and clicked search
![image](https://user-images.githubusercontent.com/750874/152750465-603a9df2-0532-48ba-b088-6eb1ae84b606.png)
4.  Typed in book > proper results display
![image](https://user-images.githubusercontent.com/750874/152750558-791332fd-9105-438b-89ad-d877fc8ecfee.png)
5. Pressed `ESC` on keyboard (without hitting a result or clicking the `x`) > this closed the modal, as expected
6. Clicked search again \
Issue is here > the book results display, even though the text box is empty

![image](https://user-images.githubusercontent.com/750874/152750972-3a2ebc61-c00a-4c99-8c92-ef7122a551d5.png)

### Theme version

latest 2.0

### Hugo version

v0.92.1

### What browsers are you seeing the problem on?

Chrome

### Relevant Hugo log output

```shell
N/A
```

**Comment by jpanther** [comment]
Thanks, this is definitely something that could be improved. I just tested this and the same behaviour happens regardless of if you press Esc or hit the close button on the search box.
