### ISSUE TITLE
Google Unparsable Structured Data

### ISSUE THREAD

**Issue by PhasecoreX** [jpanther/congo#113]
### What happened?

Google's site crawler notified me of an "unparsable structured data" issue, located on the main page. 

https://github.com/jpanther/congo/blob/e9f59082ded9c0827e204b43066d6a717cc4844f/layouts/partials/schema.html#L11-L17

Since I didn't have keywords on my home page, line 15 doesn't happen, leaving line 14 with a trailing comma that Google and JSON doesn't like:

```
<script type="[application/ld+json]()">
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": "http:\/\/localhost:1313\/",
    "name": "My Blog",
    "description": "My description",
    "inLanguage": "en",
    "url": "http:\/\/localhost:1313\/",
    "publisher" : {
      "@type": "Person",
      "name": "PhasecoreX",
    },
    
  }
  </script>
```

I figured I would try to add keywords to my blog, so I added them to my `languages.en.toml` like so:
```
keywords = ["keyword1", "keyword2", "keyword3"]
```
Not sure if this is where they are supposed to go or if it's the correct format, as I couldn't find any documentation, but it does populate it on the home page. However, it too has a trailing comma:
```
<script type="[application/ld+json]()">
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": "http:\/\/localhost:1313\/",
    "name": "My Blog",
    "description": "My description",
    "inLanguage": "en",
    "url": "http:\/\/localhost:1313\/",
    "publisher" : {
      "@type": "Person",
      "name": "PhasecoreX",
    },
    "keywords": ["keyword1","keyword2","keyword3"],
  }
  </script>
```
I think maybe it's just taking that whole list and placing it on the page as is, with that extra comma from `{{ . }},{{ end }}` after it. Thought it would loop over the values, but I guess not.

### Theme version

v2.0.4

### Hugo version

v0.92.2

### What browsers are you seeing the problem on?

Firefox

**Comment by jpanther** [comment]
Thanks, this is definitely a bug. I'll make some adjustments to try to remove these erroneous commas.

`keywords` is a Hugo front matter parameter separate to the theme. You can find the documentation on these predefined params at the official Hugo docs: https://gohugo.io/content-management/front-matter#predefined

**Comment by PhasecoreX** [comment]
Ah that makes sense, forgot that there are Hugo predefined front matter parameters. Thanks for fixing this! Very clean, just having to swap the two lines around to fix it.
