### ISSUE TITLE
Troubles with icons

### ISSUE THREAD

**Issue by MikiVanousek** [jpanther/congo#123]
### What happened?

This is my home page:
```md
Welcome to my website! I'm really happy you stopped by.

{{< icon "github" >}}
{{< icon "spotify" >}}
{{ partial "icon.html" "github" }}
```
And this is how it renders:
![image](https://user-images.githubusercontent.com/33402194/153947141-ca55f68e-87ec-4761-8b88-014968d497be.png)

As you can see, the partial does not work at all, while the custom icon does not take the font color.

Since I am already filing an issue, as a feature request, I think it would be nice to include Spotify icon, as it is a very common thing to have on your website.

### Theme version

2.0.4

### Hugo version

v0.92.1

### What browsers are you seeing the problem on?

Firefox

**Comment by jpanther** [comment]
Thanks for your report, however I don't think these issues are bugs.

In Hugo, partials cannot be used in your content as they are only for templating. Therefore you should only use shortcodes in your content, and partials in your templates (this is why the theme includes both options).

Custom icons not appearing in the correct colour is usually an issue with the SVG file you are using. See discussion https://github.com/jpanther/congo/discussions/60 for more information. I suspect this is the problem you're seeing with the Spotify icon in your example.

I can look to add the Spotify icon for you in a future update. However, please open a [discussion](https://github.com/jpanther/congo/discussions) to request new features.
