### ISSUE TITLE
Underline styles not displaying correctly in some browsers

### ISSUE THREAD

**Issue by jpanther** [jpanther/congo#125]
### Discussed in https://github.com/jpanther/congo/discussions/116

<div type='discussions-op-text'>

<sup>Originally posted by **cbelena** February 14, 2022</sup>
I have tested it on my yet-to-be-published new personal page and I have some comments/suggestions/questions about version 2:

1. I noticed there are new subtle animations when the cursor moves above links, that's nice! However, in some links I have found that the colour of the underline changes from black/white (depends on appearance) to the correct theme's colour. Is that a design choice or a bug? For example, in `exampleSite`:
![image](https://user-images.githubusercontent.com/97797388/153770952-f7a40ff6-ffeb-4a72-a332-fe9d7da100e2.png)
...and 150ms later:
![image](https://user-images.githubusercontent.com/97797388/153770981-a084263f-50c4-4e7b-b0f2-52009bc74644.png)
</div>

**Comment by cbelena** [comment]
Many thanks for fixing this! 😀
