### ISSUE TITLE
Code copy doesn't work when set `highlight.noClasses = true`

### ISSUE THREAD

**Issue by wizardbyron** [jpanther/congo#154]
### What happened?

When I set `enableCodeCopy = true`, the copy button in the code blocks stuck and prompts the following in the browser console:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'innerText')
    at copyCodeToClipboard (main.bundle.min.998bd658c4cc3498df01180704ad0ea16bb3c0d6d118eb8ac6f557a59c86d1304d69e51ba7df5a9d203e2698d28571a422b4cf20f830810d571fee19fbcb55fc.js:11:695)
    at HTMLButtonElement.<anonymous> (main.bundle.min.998bd658c4cc3498df01180704ad0ea16bb3c0d6d118eb8ac6f557a59c86d1304d69e51ba7df5a9d203e2698d28571a422b4cf20f830810d571fee19fbcb55fc.js:11:550)

### Theme version

2.1.0

### Hugo version

v0.94.2

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by wizardbyron** [comment]
I fixed this issue by remove the `querySelector(":last-child > .chroma > code").innerText;` in the `code.js` at line:16

from

```js
const codeToCopy = highlightDiv.querySelector(":last-child > .chroma > code").innerText;
```

to 

```js
const codeToCopy = highlightDiv.innerText;
```

It works but I want to know your opinion and design on it.

Look forward to reply.

Thanks.

**Comment by jpanther** [comment]
I've been trying to replicate this issue without any success. I've tried both Safari and Firefox and the current selector seems to be working fine. Is this specific to a particular browser version or configuration?

The problem with your change is that it will break the functionality of the code copy when the line numbers are enabled on the code block. If you remove `.chroma` from the selector, it will copy the line numbers instead of the actual code. There's an example of this type of code block on the Markdown Sample page in the exampleSite if you want to test to see what I mean.

**Comment by wizardbyron** [comment]
I closed the PR but the problem still problem still exists, the exampleStie has same issue. I'm trying to figure out the root cause.

**Comment by wizardbyron** [comment]
Finally, I found this issue is caused by both`noClasses = true` in `[highlight]`and `enableCodeCopy = true`.

**Comment by wizardbyron** [comment]
Here are design options:
1. Show error message when both `highlight.noClasses = true` and `.Site.Params.enableCodeCopy = true`.
2. Enforce or overwrite `highlight.noClasses = false` when `.Site.Params.enableCodeCopy = true`.

**Comment by jpanther** [comment]
Well `highlight.noClasses = false` is considered a theme requirement so I'm not sure this is actually a big problem to solve. Perhaps I could show a build warning if any of the required params aren't set though.

**Comment by jpanther** [comment]
I've had a look into this and unfortunately Hugo doesn't allow themes to access the Markup config values and so I'm not able to add these warnings - see https://discourse.gohugo.io/t/how-do-i-get-the-noclasses-value/26395. I don't think there's much more I can add to this at this stage.

**Comment by wizardbyron** [comment]
> I've had a look into this and unfortunately Hugo doesn't allow themes to access the Markup config values and so I'm not able to add these warnings - see https://discourse.gohugo.io/t/how-do-i-get-the-noclasses-value/26395. I don't think there's much more I can add to this at this stage.

It looks the only thing we can do is to update [configuration.md](https://github.com/jpanther/congo/blob/dev/exampleSite/content/docs/configuration.md) to highlight when `enableCodeCopy = true` that `highlight.noClasses` must be `false`.

**Comment by jpanther** [comment]
I have made some changes to better explain these required params. Hopefully this makes it a bit clearer and will help others avoid this situation.
