### ISSUE TITLE
Congo do not display correctly when deployed to gh-pages 

### ISSUE THREAD

**Issue by m0rphed** [jpanther/congo#169]
### What happened?

When correctly displayed locally, site do not loads correctly when deployed to gh-actions.
see example 👉[here](https://m0rphed.github.io/hugo-test/)
#### Expected (build locally with `hugo serve -D`): 
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/35064145/162096222-cd952e3b-080e-4b24-aa9a-e0f0b1878cb6.png">

#### Actually got: 
<img width="730" alt="image" src="https://user-images.githubusercontent.com/35064145/162096279-e835a464-1fa3-4661-903c-106abf90d62c.png">

### Theme version

v2.1.1

### Hugo version

v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
This is most likely because your `baseURL` parameter is not set correctly. If you inspect the console output for your GitHub pages site, the URLs that are failing do not include the `/hugo-test/` part of the path.

**Comment by m0rphed** [comment]
> This is most likely because your `baseURL` parameter is not set correctly. If you inspect the console output for your GitHub pages site, the URLs that are failing do not include the `/hugo-test/` part of the path.

Do you mean that baseURL should be set to: `<user>.github.io/<repo-name>` ( `https://m0rphed.github.io/hugo-test` in my case) when we want to deploy it to GitHub Pages?

**Comment by jpanther** [comment]
Yes, correct. You can either set it in the config file or pass it as a parameter to the build command. If you look at [`gh-pages.yml`](https://github.com/jpanther/congo/blob/dev/.github/workflows/gh-pages.yml) in the project you can see an example of how the docs site is deployed to GitHub Pages using the build parameter.

**Comment by jpanther** [comment]
It looks like you managed to get this working so I'll go ahead and close this one.

**Comment by m0rphed** [comment]
Yes, thank you!
Providing `--baseURL https://<user>.github.io/<repo>/` in GitHub Pages `.yml`-file solves the problem for me 😄 
However, setting `baseURL` in config didn't solve it, maybe it's worth mentioning in docs that when you deploy to _gh-pages_ it it necessary to provide `--baseURL` flag
