### ISSUE TITLE
"Scroll To Top" overlaps footer menu on mobile devices

### ISSUE THREAD

**Issue by chibiribiri** [jpanther/congo#172]
### What happened?

If footer menu is activated, the Scroll to top position is above the copyright instead being on the same line:

![Webaufnahme_10-4-2022_13827_dev1 kachiri de](https://user-images.githubusercontent.com/58009927/162615290-4e99f809-2d35-48fc-ac2b-8cc082283b82.jpeg)

For the view on mobile devices it means, that the Scroll to top button overlaps the footer menu:

![IMG_3461](https://user-images.githubusercontent.com/58009927/162615372-48cefdd6-b76f-4723-ab34-40b556d306cc.PNG)
29-911c-c988c899d30d.jpeg)

### Theme version

v2.1.2

### Hugo version

v0.96.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by jpanther** [comment]
Thanks for the report @chibiribiri. This is definitely a bug. I'll include a fix in the next release.

**Comment by chibiribiri** [comment]
First point is fixed. Seems like the button is now on line with the copyright.
Thanks!

On mobile devices (atleast iOS/Safari) the positioning got better but I think there's still room for improvement :)

![IMG_3463](https://user-images.githubusercontent.com/58009927/163156004-0a1dd0bd-7ab7-4f98-a601-c4413d48b633.PNG)

**Comment by jpanther** [comment]
Thanks for the screenshot. I think I know why this is happening, I'll make further changes to try to address it.
