### ISSUE TITLE
The image provided by `params.logo` is not resized.

### ISSUE THREAD

**Issue by slashformotion** [jpanther/congo#19]
### What happened?

Example: 
![image](https://user-images.githubusercontent.com/45801817/138920373-483a30da-a52c-44ba-870e-a2e7fc5ce8ce.png)

thoses are the exact sames images if you are wondering 

It should probably be resized.

### Theme version

v1.4.0

### Hugo version

v0.86.1

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
I guess this technically isn't a bug as I assumed people would provide a logo that would be a suitable size for their design intent. I can see why this is a potential issue though.

One of the challenges here is that logos can be varied in how they are used and I'm trying to keep it flexible in terms of allowing any aspect ratio. The compromise is to set max width and height parameters on these and take the trade-off that it will reduce the flexibility in some situations.

**Comment by slashformotion** [comment]
ok thanks for the answer

> The compromise is to set max width and height parameters on these and take the trade-off that it will reduce the flexibility in some situations.

Seems the best of both world

**Comment by jpanther** [comment]
I've added some constraints to the logo and it will now scale down images that are too large in either dimension. The maximum dimensions are capped at 10rem which under default circumstances translates to 160 x 160px.

**Comment by schperplata** [comment]
I am having a problem with this default constraint: my logo is not square, but rectangular, for example 640x70px.  With current default (max) value, 160px in width scale down logo way too much, making too small.
Is there a any way to override logo dimensions?
