### ISSUE TITLE
[Bug] Open pages with a sudden dark flash, both in light theme and dark theme.

### ISSUE THREAD

**Issue by Kord64** [jpanther/congo#196]
### What happened?

When opening the pages generated by the theme Congo, **a sudden dark flash** occurred.

![screen-record-2022-05-13-00-29](https://user-images.githubusercontent.com/93251479/168124925-bb8de0ed-d1d7-41dd-854a-7889e751f598.gif)

Here it is what it looks like on Safari. Also the problem occurs on Chrome but not that obvious.

<img width="869" alt="Screen Shot 2022-05-13 at 00 29 09" src="https://user-images.githubusercontent.com/93251479/168125025-74904cf6-9e86-4aa7-98dd-5145c2debdf8.png">

### Theme version

2.2.0

### Hugo version

0.87.0

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by jpanther** [comment]
Thanks for the report, @Kord64. Could you please try upgrading your Hugo version to see if this issue still persists?

It'd also be helpful to know more about when you are seeing this... 

- Are you running locally or is this hosted?
- What are your dark mode config parameters set to?
- Are there any errors being output to the console in your browser?

**Comment by Kord64** [comment]
Thank you for your reply. The website is running locally and the output information is fine.

It seems I probably find the reason why. There is a browser plugin called **Darkreader**,which can enable dark theme for most websites. But when it is enabled, it somehow would have conflicts with the original dark or light theme of the website. 

Basically the original dark theme of the website immediately takes effect when the site is loaded, then the plugin takes effect  afterwards. So *the latency of the plugin taking effect* is the problem of the flash, instead of the theme.

Thank you for the beautiful theme and have a nice day 🧡.
