### ISSUE TITLE
Profile layout doesn't fit to page

### ISSUE THREAD

**Issue by UnicornsOnLSD** [jpanther/congo#201]
### What happened?

Recently updated to Congo 2.2, and my homepage (https://jmshrv.com/ - source at https://github.com/UnicornsOnLSD/UnicornsOnLSD.github.io/) no longer expands to fit the whole page. Instead, it fits to the top of the page.

### Theme version

2.2.0

### Hugo version

0.99.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant Hugo log output

```shell
Start building sites … 
hugo v0.99.1-d524067382e60ce2a2248c3133a1b3af206b6ef1 linux/amd64 BuildDate=2022-05-18T11:18:14Z VendorInfo=gohugoio

                   | EN-GB  
-------------------+--------
  Pages            |    13  
  Paginator pages  |     0  
  Non-page files   |     0  
  Static files     |     7  
  Processed images |     6  
  Aliases          |     1  
  Sitemaps         |     1  
  Cleaned          |     0  

Total in 399 ms
```

**Comment by jpanther** [comment]
Thanks for the report. This is definitely a bug. I'll make some style adjustments to restore the old behaviour.
