### ISSUE TITLE
REF_NOT_FOUND: Ref "docs/shortcodes"

### ISSUE THREAD

**Issue by qingruoyu** [jpanther/congo#203]
### What happened?

Congo theme is installed via git on Windows 11, as folow as https://jpanther.github.io/congo/docs/installation/#install-using-git. and configured the folder config/ .There was no problem at first when try to run it locally, using `.\hugo.exe server -t congo --buildDrafts`, but adding some files under concent/, the following error occurred. I know that docs/ and samples/ are sample files, so I put the missing files  into the folder concent/ , sometimes without error, and more often as a similar error, even though the files are already there.
Hope to solve this trouble.
```
Change of config file detected, rebuilding site.
2022-05-23 22:40:14.545 +0800
ERROR 2022/05/23 22:40:14 [en] REF_NOT_FOUND: Ref "docs/configuration": "E:\test\BBlog\content\docs\version-2\upgrade\index.md:175:73": page not found
ERROR 2022/05/23 22:40:14 [en] REF_NOT_FOUND: Ref "docs/shortcodes": "E:\test\BBlog\content\docs\version-2\upgrade\index.md:192:30": page not found
ERROR 2022/05/23 22:40:14 [en] REF_NOT_FOUND: Ref "docs/shortcodes": "E:\test\BBlog\content\samples\charts.md:15:32": page not found
ERROR 2022/05/23 22:40:14 [en] REF_NOT_FOUND: Ref "docs/shortcodes": "E:\test\BBlog\content\samples\diagrams-flowcharts.md:15:34": page not found
ERROR 2022/05/23 22:40:14 [en] REF_NOT_FOUND: Ref "docs/partials": "E:\test\BBlog\content\samples\icons.md:15:170": page not found
ERROR 2022/05/23 22:40:14 [en] REF_NOT_FOUND: Ref "docs/shortcodes": "E:\test\BBlog\content\samples\icons.md:15:224": page not found
ERROR 2022/05/23 22:40:14 [en] REF_NOT_FOUND: Ref "docs/shortcodes": "E:\test\BBlog\content\samples\mathematical-notation.md:18:167": page not found
ERROR 2022/05/23 22:40:14 [en] REF_NOT_FOUND: Ref "docs/installation": "E:\test\BBlog\content\_index.md:30:216": page not found
ERROR 2022/05/23 22:40:14 [en] REF_NOT_FOUND: Ref "docs/installation": "E:\test\BBlog\content\docs\version-2\_index.md:96:169": page not found
ERROR 2022/05/23 22:40:14 logged 9 error(s)
```

### Theme version

v2.2

### Hugo version

v0.99.1

**Comment by jpanther** [comment]
Thanks for the report. Are you simply trying to build the example site? Do you get these errors if you use the command `npm run example` from inside the theme directory?

**Comment by qingruoyu** [comment]
There is nothing wrong with the example site. I seem to have found the problem where is. The content I added points to a link `({{< ref\ "tags\" >}})`, and there is no file to point to, so errors is reported. This is my negligence. I'm so sorry for wasting your time. Looking forward to your theme getting better and better.

**Comment by jpanther** [comment]
Okay, thanks for the update. I'll go ahead and close this.
