### ISSUE TITLE
Update not working (as Hugo module)

### ISSUE THREAD

**Issue by antomal** [jpanther/congo#228]
### What happened?

Update not working ([as Hugo module](https://jpanther.github.io/congo/docs/installation/#update-using-hugo)).

```
hugo mod get -u
go: module github.com/jpanther/congo/v2: git ls-remote -q origin in /var/folders/gs/m9z38b6d7w9bdp6tgt0r82bh0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/cache/vcs/066af87f3ece5bb7d6b6b53ce98f8b34566e9be8285986a3e33bbfe82661fac4: exit status 128:
	fatal: 'origin' does not appear to be a git repository
	fatal: Could not read from remote repository.
	
	Please make sure you have the correct access rights
	and the repository exists.
Error: failed to get ["-d" "-u" "github.com/jpanther/congo/v2"]: failed to execute 'go [get -d -u github.com/jpanther/congo/v2]': failed to execute binary "go" with args [get -d -u github.com/jpanther/congo/v2]: go: module github.com/jpanther/congo/v2: git ls-remote -q origin in /var/folders/gs/m9z38b6d7w9bdp6tgt0r82bh0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/cache/vcs/066af87f3ece5bb7d6b6b53ce98f8b34566e9be8285986a3e33bbfe82661fac4: exit status 128:
	fatal: 'origin' does not appear to be a git repository
	fatal: Could not read from remote repository.
	
	Please make sure you have the correct access rights
	and the repository exists.
 *errors.errorString
```

If you click on the link [github.com/jpanther/congo/v2](https://github.com/jpanther/congo/v2) - Error 404.
How to update now?

### Theme version

2.2.3

### Hugo version

0.101.0

### What browsers are you seeing the problem on?

Safari

**Comment by jpanther** [comment]
I suspect this is an issue either with your local git configuration or Go. Have you tried running `hugo mod clean`? This will empty out any caches in case something has gone amiss.

I would expect `github.com/jpanther/congo/v2` to 404 as that is the location that go is using to find the module, not what git is using to locate the repo.

**Comment by antomal** [comment]
Hmm... I just entered command `hugo mod clean` and **it worked**, BUT it didn't work yesterday. 🤔

> I would expect `github.com/jpanther/congo/v2` to 404 as that is the location that go is using to find the module, not what git is using to locate the repo.

Interesting. Read something about it (how it works).

Thank you!
