### ISSUE TITLE
Search in primary language only?

### ISSUE THREAD

**Issue by antomal** [jpanther/congo#229]
### What happened?

My site is bilingual, but only primary language pages appear in search results.

### Theme version

2.2.3

### Hugo version

0.101.0

**Comment by jpanther** [comment]
Thanks for the report. I've been able to reproduce this bug. The search is meant to search any articles in the active language but there's a minor URL issue where it's missing the language prefix and so it falls back to only using the primary language. This will be fixed in the next release.
