### ISSUE TITLE
Hugo v0.101 breaks the HOMEPAGE link.

### ISSUE THREAD

**Issue by MikiVanousek** [jpanther/congo#230]
### What happened?

When building the site with `Hugo v0.99` everything works as expected. But when `Hugo v0.101` is used, the link to the home of the page does not lead to the desired `./webiste`, but to `./`. All other links work as expected. **The issue was resolved by switching to the `dev` branch**.

### Theme version

v2.2.3

### Hugo version

v0.101

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by MikiVanousek** [comment]
@Yawar5

**Comment by jpanther** [comment]
Thanks for the report. Yes, the `dev` branch contains a change that I suspect is what has fixed this issue - 971e8b631d4f87376e2c07731aa206f183f6728f.

I guess something changed in the way Hugo interprets any paths that start with a forward slash as a local path and so using `"/"` to link to the homepage breaks the way it generates the URL.

The fix will be included in the next release.

**Comment by MikiVanousek** [comment]
Considering that GH pages uses `Hugo v0.101`, everyone's page will be broken after the first push. For this reason, I think it would be wise to release the update ASAP, even if it would be the only change in the next release.

The error was encountered by my friend, who is not that tech-savvy. He spent a considerable amount of time trying to fix it. Encountering an issue like this while first setting up your website could cause someone like him to abandon the theme altogether.

I would even consider putting a temporary announcement into the README / documentation, to let people who are struggling with this issue know you can fix it by updating the theme.

**Comment by jpanther** [comment]
The update will be out very soon and I'm committing a change that specifically calls out this issue in the changelog.
