### ISSUE TITLE
i can't add comments

### ISSUE THREAD

**Issue by wsdydeni** [jpanther/congo#239]
### What happened?

i add comments.html,but it did not show.

### Theme version

lasted

### Hugo version

hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

### What browsers are you seeing the problem on?

Chrome

### Relevant Hugo log output

```shell
no everything
```

**Comment by jpanther** [comment]
Where in your project have you placed the `comments.html` file? It needs to be in `layouts/partials/comments.html` in order to be picked up by the theme.

You also need to ensure `showComments` is set to `true` in your theme configuration or in the article front matter.

**Comment by wsdydeni** [comment]
> Where in your project have you placed the `comments.html` file? It needs to be in `layouts/partials/comments.html` in order to be picked up by the theme.
> 
> You also need to ensure `showComments` is set to `true` in your theme configuration or in the article front matter.

I'm sorry,i don't know this file should in theme folder or project folder.

**Comment by wsdydeni** [comment]
`comments.html` should be in the project folder,i'm sorry.
