### ISSUE TITLE
.LastMod display logic is not useful with .GitInfo

### ISSUE THREAD

**Issue by mika-fischer** [jpanther/congo#259]
### What happened?

https://github.com/jpanther/congo/commit/a041f09f6f9aabccc85f8f3eeef84b59828080b1 improved the display of `.LastMod` so that it's only displayed when different from `.Date`.

However, when using `.GitInfo` to automatically populate `.LastMod` from the date of the last commit touching the file in question, this logic pretty much never fires and `.LastMod` is *always* displayed.

What's really needed is to display `.LastMod` only if the *formatted* `.LastMod` is different from the *formatted* `.Date`.

If that's difficult, it would help to change the `ne` [here](https://github.com/jpanther/congo/blob/d045d025474e9e3c56d600a1a1ac73e79ec0816f/layouts/partials/article-meta.html#L19) to a `lt` so that I can manually set the article date to a date after the commit that published the article and prevent the display of .LastMod this way.

### Theme version

v2.3.1

### Hugo version

v0.101.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by jpanther** [comment]
Thanks for the report, @mika-fischer. I'll make a change so that both dates are formatted prior to checking their values. Hopefully this will address the issue you're seeing.
