### ISSUE TITLE
Appearance switcher has no effect on Cloudflare Pages

### ISSUE THREAD

**Issue by major** [jpanther/congo#266]
### What happened?

My appearance switcher (sun/moon) worked well when I ran `hugo serve` locally, but after publishing to Cloudflare pages, the switcher has no effect. I can click it as much as I want in Chrome or Firefox, but nothing happens. There's nothing in my browser's local storage, either.

My site: https://major.io

### Theme version

2.3.1

### Hugo version

0.101.1

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by major** [comment]
My current set of params: https://github.com/major/major.io/blob/main/config/_default/params.toml

**Comment by major** [comment]
Ah, I figured out what it was! It's Cloudflare's [Rocket Loader](https://support.cloudflare.com/hc/en-us/articles/200168056) feature. It shortens the time for a content paint with javascript, but I think it was causing something to be loaded out of order with the appearance toggle.

To fix it, one must go into Cloudflare's dashboard and:

- Click the website where they deployed Hugo/Congo
- Click *Speed* on the left bar
- Click *Optimization* in the *Speed* section
- Scroll to *Rocket Loader™* and turn it off
- Clearing cache may be necessary, but it wasn't needed for me

I doubt there's a bug with Congo here, but I'd be glad to write a little warning in the Congo docs about it if someone might find it useful. 😉

**Comment by jpanther** [comment]
Thanks for the report. I've never tried deploying a Hugo site to Cloudflare Pages. If you feel like adding some documentation to the Hosting and Deployment page that explains how to deploy a site (and include a comment about this Rocket Loader issue) that would definitely be something that could help others. Feel free to submit a PR. In the meantime I'll close off this issue as I don't think anything needs to be changed in the theme.

**Comment by major** [comment]
@jpanther I'll do that. Thank you.
