### ISSUE TITLE
Black YouTube embed when returning to the previous page in safari

### ISSUE THREAD

**Issue by antomal** [jpanther/congo#270]
### What happened?

1. Open the page with the embedded YouTube video.
2. Go to another page
3. Going back.

YouTube blocks are black.

Example page https://jpanther.github.io/congo/samples/rich-content/
![Kapture 2022-08-11 at 01 47 17](https://user-images.githubusercontent.com/44556749/184036919-0bb352e3-056b-4952-854d-2c4f3527c94c.gif)

In Chrome everything is fine, but the problem in Safari 15.6 (17613.3.9.1.5)

Tried embedding youtube shortcode and directly embed code (from the site youtube).

### Theme version

2.3.1

### Hugo version

0.101.1

**Comment by jpanther** [comment]
I'm not sure why you're seeing this issue but I'm not able to replicate it. I'm using Safari with the same version as you and if I follow the same steps as your video the YouTube embed loads fine when I go back. Are you sure you don't have a browser extension or something that might be causing this problem?

**Comment by antomal** [comment]
Yes. You're right.
It's working now. Google may have had a problem.
