### ISSUE TITLE
Pagination Overflows

### ISSUE THREAD

**Issue by pitermarx** [jpanther/congo#299]
### What happened?

![image](https://user-images.githubusercontent.com/3081298/191947564-2e8f3df1-8282-4f86-8ecb-3e0bc54cebcc.png)

Should pagination follow the pattern ?

< 1 2 3 4 5 ... 123 >

### Theme version

2.3.1

### Hugo version

0.102.3

### What browsers are you seeing the problem on?

Chrome

**Comment by pitermarx** [comment]
see live in https://pitermarx.github.io/posts/
and source here https://github.com/pitermarx/pitermarx.github.io/

**Comment by jpanther** [comment]
Thanks for the report. This is definitely a bug that will be fixed!

**Comment by pitermarx** [comment]
possible fix
https://github.com/pitermarx/pitermarx.github.io/blob/master/layouts/partials/pagination.html

**Comment by jpanther** [comment]
I haven't had time to look at this just yet, but it's still on the radar.
