### ISSUE TITLE
Page with just video. Video disapears on large screens

### ISSUE THREAD

**Issue by pitermarx** [jpanther/congo#302]
### What happened?

![demo](https://user-images.githubusercontent.com/3081298/192151766-0e6bfa8f-c427-40bc-946d-a3733ce0f59d.gif)

https://pitermarx.github.io/2022/09/can-lego-play-the-drums/
I had the issue here but wrapped the youtube shortcode in a div like this

`<div style="width:70vw">{{< youtube ...>}}</div>`

### Theme version

2.3.1

### Hugo version

0.102.3

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
Thanks for the report, I can replicate this in other browsers too. I'll see if there's a way I can address this in the theme as the shortcode is simply the default Hugo version.

**Comment by pitermarx** [comment]
I ended up setting a fixed 90% width on the .max-w-prose
