### ISSUE TITLE
Missing Tailwind classes, e.g. border

### ISSUE THREAD

**Issue by bshyong** [jpanther/congo#304]
### What happened?

There are some missing Tailwind classes 

confirmed missing:
- `py-4` (though py-1, py-2, py-3 are availble)
- the border classes `border-solid`, `border-2`, `border-sky-500`, etc.

I've tried debugging and can't figure out why this is happening; some of these classes are simply unrecognized in the theme while others seem to work. 

### Theme version

v2.3.1

### Hugo version

 v0.104.2

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari, all browsers

**Comment by opncow** [comment]
Only the classes the theme already uses are included by default. Try with building the theme CSS from source: https://jpanther.github.io/congo/docs/advanced-customisation/#building-the-theme-css-from-source

**Comment by bshyong** [comment]
Got it, thank you
