### ISSUE TITLE
Ordering content in a list layout

### ISSUE THREAD

**Issue by gtitov** [jpanther/congo#313]
### What happened?

Hey! The theme is awesome. I faced some minor issues ordering content in a list layout. I'm not sure if they can be considered bugs but I wanted to share.

#### Order by date before weight

While default Hugo behavior is to order content by [weight > date > title > filename](https://gohugo.io/templates/lists/#default-weight--date--linktitle--filepath) Congo seems to order content by date > weight > ... So if `date` exists in a frontmatter `weight` is ignored.

#### Order by weight goes bottom-to-top

When there is no dates in posts Hugo orders content by weight. But content with lower weight comes lower in the list while Hugo docs says ["Lower weight gets higher precedence."](https://gohugo.io/templates/lists/#by-weight). So I expected a page with the lowest weight to appear first but it appears last in a list with the Congo theme.

### Theme version

v2.3.0

### Hugo version

v0.101.0

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
Thanks for the detailed report. I'll take a look at these and see if there's any adjustments to be made that can improve the output. In general, I try to stick to the default Hugo behaviours as much as possible.

**Comment by gtitov** [comment]
A bit of a research showed that this line is responsible for the issue if it helps somehow

https://github.com/jpanther/congo/blob/a74a40190ae87a7cfbef3db7a8e2a9300acea2c8/layouts/_default/list.html#L29
