### ISSUE TITLE
KaTeX doesn't render $$ blocks

### ISSUE THREAD

**Issue by Benjamin-Lee** [jpanther/congo#316]
### What happened?

Minimal example:

```md
---
title: KaTeX Test
---

{{< katex >}}

\\(\LaTeX\\)

$\LaTeX$
```

Output:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/13618205/195269386-36879560-703c-49ee-a7b7-4b2d6d80b9b0.png">

### Theme version

v2.3.1

### Hugo version

v0.104.3

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by jpanther** [comment]
Thanks for the report @Benjamin-Lee, however this is not a bug. The KaTeX extension does not support single dollar sign delimiters by default as the dollar symbol appears too frequently in normal text - see discussion here: https://github.com/KaTeX/KaTeX/issues/712. You can also read more about the default delimiters that are available by consulting the [KaTeX auto-render docs](https://katex.org/docs/autorender.html).

If you wish to make use of other delimiters, you'd have to provide your own configuration to the KaTeX extension.

**Comment by AppleGamer22** [comment]
Hi @Benjamin-Lee, if you are certain that you'll use single dollar signs only for inline KaTeX blocks, I [wrote](https://github.com/AppleGamer22/applegamer22.github.io/blob/master/layouts/partials/extend-head.html) an HTML extension for Congo that might achieve what you need. I also acknowledge that this implementation is fairly similar to the code from the KaTeX documentation that James shared. It has some limitations, but they mainly concern multi-line KaTeX blocks (such as `align*`), and to the fact that the KaTeX assets are fetched on all pages. I have a demo for it on my [website](https://applegamer22.github.io/posts/configurations/congo/#katex).
