### ISSUE TITLE
Back to top button glitches with Firefox

### ISSUE THREAD

**Issue by gcailly** [jpanther/congo#319]
### What happened?

Hi,
First, thanks for Congo, which is a great theme !
I read Congo documentation on my phone with the latest Firefox. But the "back to top" button glitches. There was some slowness when scrolling the page, which was not present when this button was not present (like on small pages).
Here is a video :
https://drive.google.com/file/d/13_cR24L0UKwvkEeTHVL2Wtj2TTIDBevu/view?usp=sharing

### Theme version

2.3.1 ?

### Hugo version

yours

### What browsers are you seeing the problem on?

Firefox

**Comment by jpanther** [comment]
I haven't been able to replicate this issue. Is it only happening in certain versions of Firefox?

**Comment by gcailly** [comment]
Thank you for your response.
It was with Firefox Mobile.
I tried it now and there is no more glitch, maybe it was a Firefox problem.
Nonetheless, on my cellphone the transparency/blur of the "back to top" icon seems to slow down the scrolling of the window. When there is no "back to top" icon the scrolling is smooth. It's not chen the button is present. I have a 2022 mid-end phone.

**Comment by jpanther** [comment]
I've tried this just now using Firefox Mobile and I still can't replicate this problem. The scrolling is perfectly smooth for me when the link is present. Here's a quick video...

https://user-images.githubusercontent.com/4462786/200461620-0bafc91c-e45e-4bc5-813f-d70b0cc3fa65.mov

**Comment by gcailly** [comment]
Here is my capture. The first part (home page) is very fast. The second part (some Documents page) lags a little when scrolled ; it's less perceptible on the video than in real.

https://drive.google.com/file/d/17Hg4GUOtOKtk2Zm-QjzynhMAsw64G3m8/view?usp=share_link

It's not a big problem and it could be my phone.
Thank you for your support and for all your work on Congo.

**Comment by jpanther** [comment]
The link to the video doesn't appear to work. I wonder if this is a performance issue with the device related to calculating the opacity on the button.

**Comment by gcailly** [comment]
Here is a Youtube link : https://youtu.be/yBADVUpCELc

**Comment by gcailly** [comment]
I think it's a Firefox problem : I tried in Chrome and no slowness.
Thank you again for your amazing work and the new versions of Congo.
