### ISSUE TITLE
hugo-shortcode-gallery layout not working properly with Congo theme

### ISSUE THREAD

**Issue by sjohner** [jpanther/congo#335]
### What happened?

I was able to setup a [hugo-shortcode-gallery](https://github.com/mfg92/hugo-shortcode-gallery) with congo but struggle with the layout of the gallery. Above a certain resolution (width > 1023px) somehow the images of the gallery do not align as intended. Instead of being displayed as a gallery, they are simply displayed one by one below each other and the rowHeight parameter has no effect on the gallery anymore. Below width 1024px the gallery works as expected (see screenshots below).

I guess it has something to do with these lines of CSS https://github.com/jpanther/congo/blob/cc5807bde0f36c77b4b0c36a3dbabbac4308d371/assets/css/compiled/main.css#L3138-L3140
Commenting them out seems to help but I'm not sure what else this will break :-) Can anyone shed more light on this?

<img width="808" alt="193479867-48c8cedc-19ac-44ac-ad1d-af804365dfcd" src="https://user-images.githubusercontent.com/16019080/197611939-afc17258-b468-4b26-8d73-313aaa8d50c9.png">

<img width="811" alt="193479893-8006094d-53ce-4caa-b20e-73a774deee2a" src="https://user-images.githubusercontent.com/16019080/197611961-5d1e862d-4ec0-44a8-97f3-e50903a05298.png">

### Theme version

v2.3.1

### Hugo version

0.104.2+extended

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by jpanther** [comment]
Thanks for the report. I believe this is fixed by a84e0049fca20ea7becf57c76289558e98d4bd59, which allows embedded content to fill the page area. Previously content was being truncated to the widest item on the page, which in your example is the text "Image Gallery 2022" and that is why the images are no wider than that text.
