### ISSUE TITLE
TOC and button overlapping

### ISSUE THREAD

**Issue by AntoineSoetewey** [jpanther/congo#337]
### What happened?

Hello,

When the TOC is folded and no button is present, everything is fine:

![B1B09A12-C218-4F21-9621-58ED5BA8AF61](https://user-images.githubusercontent.com/17910063/198119745-71466d23-311c-4aff-a0d8-5080f885be27.png)

However, when there is a button just below the TOC, they seem to be overlapping:

![0810C2B1-B4FD-4EB0-B903-4B8DC4EB8583](https://user-images.githubusercontent.com/17910063/198119581-2a89e0a3-d0e0-4883-9c2f-b9c6d7757a87.png)

I guess I could add a space with `<br>` but I just wanted to let you know in case it’s not the desired output.

If needed, the repo is available at https://github.com/AntoineSoetewey/antoinesoetewey.com.

Mandy thanks again for this theme!

### Theme version

v2.3.1

### Hugo version

Not sure

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
Thanks for the report. I'll address this in a future update.
