### ISSUE TITLE
Add image preview for leaves in branch page

### ISSUE THREAD

**Issue by kevinlinxc** [jpanther/congo#338]
### Discussed in https://github.com/jpanther/congo/discussions/336

<div type='discussions-op-text'>

<sup>Originally posted by **kevinlinxc** October 25, 2022</sup>
So leave pages can easily have images inside them, but it seems like the branch page only has text preview?

This is what I'm imagining, just a standard thumbnail to go with each leaf pages title:
![image](https://user-images.githubusercontent.com/44324811/197934057-17206b45-710e-48cc-b72e-1145c53234f6.png)

</div>

**Comment by jpanther** [comment]
Thanks, as this is a feature request, this is something to discuss using GitHub Discussions.
