### ISSUE TITLE
Update to hugo v0.105.0+extended darwin/amd64 error

### ISSUE THREAD

**Issue by tresero** [jpanther/congo#342]
### What happened?

I just updated on my macos and now my site locally is completely messed up.

Many of these:

WARN 2022/11/02 15:21:59 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2022/11/02 15:21:59 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2022/11/02 15:21:59 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2022/11/02 15:21:59 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2022/11/02 15:21:59 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2022/11/02 15:21:59 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2022/11/02 15:21:59 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

And going to localhost:1313 shows 404, the only thing changed was upgrade of hugo.

It also appears to only happen with your theme. Using other themes there is no problem.

### Theme version

v2.3.2

### Hugo version

v0.105.0+extended

**Comment by tresero** [comment]
If I install locally, everything works. It appears to be something with the way you are loading modules. I don't understand modules well enough to do any debugging, but if I use bilberry theme as a module it works as well. I guess it's the different way they are loading modules.

**Comment by jpanther** [comment]
Hi @tresero, do you have a repo for this project that I could take a look at? This could be a similar issue to #347

**Comment by tresero** [comment]
I don't, I didn't have time to troubleshoot, but it isn't color. It's a module issue I'm sure. I have a local version on my machine, but it's not in a repository. I switched to a different theme.

**Comment by jpanther** [comment]
Okay, no worries. I'll close this issue for now as I'm not able to replicate it but if you do decide to try Congo again, please let me know if you have this issue again.
