### ISSUE TITLE
Missing `theme-color` meta tag

### ISSUE THREAD

**Issue by wemiprog** [jpanther/congo#343]
### What happened?

First, very cool theme!

The auto darkmode is very nice. But it has one problem, especially on iPhone, (when darkmode enabled), there is a white surrounding when you zoom the tab in.

What is missing (I tested it that way and it worked) is:
```
<meta name="theme-color" media="(prefers-color-scheme: light)" content="white" />
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#1f2937" />
```
The second color (#1f2937) seems to be the default background color, this could be replaced with the background color var.

can you add this to the default head in each generated html?

Is there a possibility to add it to the generator myself as long as you it isn't fixed?

I only modified the generated file.

### Theme version

latest

### Hugo version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant Hugo log output

```shell
-
```

**Comment by jpanther** [comment]
Thanks for the report. I'm aware that the theme currently doesn't include the `theme-color` meta tag however this has been by choice. The issue with this tag is that it will reskin certain browsers and that can have unintended consequences depending on the colour scheme being used in the theme and the auto-switching dark mode.

I haven't been able to settle on a clean way to implement this without having these side effects. You can certainly include this in your own site though by using the [`extend-head.html` partial](https://jpanther.github.io/congo/docs/partials/#head-and-footer).

**Comment by jpanther** [comment]
After a little bit of research, I've created PR #379 to add basic support for this feature.
