### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by AntoineSoetewey** [jpanther/congo#35]
### What happened?

I added the google scholar icon. However, the color is different than the ones you provided:

![Screenshot 2021-11-22 at 18 17 05](https://user-images.githubusercontent.com/17910063/142905979-f3e8b974-3d1e-4853-898d-5e8e9d8b2157.png)

Any idea how I could fix this?

FYI, the repository of my website is available at : https://github.com/AntoineSoetewey/antoinesoetewey.com

### Theme version

last

### Hugo version

last

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
Hey @AntoineSoetewey, it looks like this is an issue with your SVG file. There's a lot of unnecessary metadata in the icon file, and in particular it's missing the `fill="currentColor"` from the SVG path attribute. If you add that in, it should inherit the correct styles from the theme. You can compare with the icons that are bundled with the theme as a guide.

**Comment by AntoineSoetewey** [comment]
Thanks for your prompt reply!

Fixed with https://github.com/AntoineSoetewey/antoinesoetewey.com/commit/66d25c281627c526e95413a12052d18e7c455ac1
