### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by AntoineSoetewey** [jpanther/congo#36]
### What happened?

Hello,

Even after following the steps mentioned in the [docs](https://jpanther.github.io/congo/docs/partials/#favicons), I can't display my favicon.

All files are in [`/static`](https://github.com/AntoineSoetewey/antoinesoetewey.com/tree/master/static), is it the right place?

Thanks in advance for your help !

### Theme version

last

### Hugo version

last

**Comment by jpanther** [comment]
I just checked https://antoinesoetewey.com and the icon appears for me? Are you sure this isn't a caching issue in your browser?

![Screen Shot 2021-11-23 at 08 53 14](https://user-images.githubusercontent.com/4462786/142940717-48bcf768-c427-4a5c-83be-833886f17334.JPG)

**Comment by AntoineSoetewey** [comment]
Yes I was too impatient, thanks again!

(Great theme!)

**Comment by jpanther** [comment]
No problem!
