### ISSUE TITLE
List page doesn't render nested list pages

### ISSUE THREAD

**Issue by gtitov** [jpanther/congo#365]
### What happened?

A list page doesn't render nested list pages. No errors in Hugo log output.

```
.
└── content
    └── _index.md
    └── about
        ├── _index.md
        ├── background
            └── index.md
        ├── staff
            ├── _index.md
            ├── first-staff-member.md
            └── another-staff-member.md
```

In this example it doesn't render the `staff` element in the `about` list page

I'm sorry to say but it seems like my own PR #317 did it 😞 I can't figure out why though.

### Theme version

v2.4.0

### Hugo version

v0.101.0

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by jpanther** [comment]
This does seem like a regression and I didn't catch this when I was testing the change. I'll have a look and see if I can work out where it has gone wrong.
