### ISSUE TITLE
Pagination bar is duplicated in term page

### ISSUE THREAD

**Issue by younsl** [jpanther/congo#366]
### Syptom
Pagination bar is duplicated in term page.
This bug appeared after upgrading from congo `v2.3.1` to `v2.4.0.`

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/87736192/201500082-759b0660-0186-4c24-8588-24ca4c08e4e0.png">

###  Workaround

To solve this bug, I found a simple workaround.
But I don't know if this is a good way. (just take note)

**layouts/_default/term.html**

```diff
{{ define "main" }}
  <header>
    {{ if .Params.showBreadcrumbs | default (.Site.Params.list.showBreadcrumbs | default false) }}
      {{ partial "breadcrumbs.html" . }}
    {{ end }}
    <h1 class="mt-0 text-4xl font-extrabold text-neutral-900 dark:text-neutral">{{ .Title }}</h1>
  </header>
  {{ if .Content }}
    <section class="flex flex-col max-w-full mt-0 prose dark:prose-invert lg:flex-row">
      <div class="min-w-0 min-h-0 max-w-prose grow">
        {{ .Content | emojify }}
      </div>
    </section>
  {{ end }}
  <section>
    {{ if .Data.Pages }}
      <section>
        {{ if $.Params.groupByYear | default ($.Site.Params.list.groupByYear | default true) }}
          {{ range (.Paginate (.Pages.GroupByDate "2006")).PageGroups }}
            <h2 class="mt-12 text-2xl font-bold text-neutral-700 first:mt-8 dark:text-neutral-300">
              {{ .Key }}
            </h2>
            <hr class="border-dotted w-36 border-neutral-400" />
            {{ range .Pages }}
              {{ partial "article-link.html" . }}
            {{ end }}
          {{ end }}
        {{ else }}
          {{ range .Paginator.Pages }}
            {{ partial "article-link.html" . }}
          {{ end }}
        {{ end }}
      </section>
      {{ partial "pagination.html" . }}
    {{ else }}
      <section class="mt-10 prose dark:prose-invert">
        <p class="py-8 border-t">
          <em>{{ i18n "list.no_articles" | emojify }}</em>
        </p>
      </section>
    {{ end }}
  </section>
- {{ partial "pagination.html" . }}
{{ end }}
```

And then, the pagination bar works normally on the term page.

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/87736192/201500206-f33f3937-d027-42d6-aa1e-af1202135cd1.png">

### Reference

Fix error calling Paginate #289 

### Theme version

v2.4.0

### Hugo version

hugo v0.105.0+extended darwin/arm64 BuildDate=unknown

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by jpanther** [comment]
Thanks for the report, @seyslee. This is definitely an oversight on my part. I'll patch it in the next release.
