### ISSUE TITLE
Inline backticked code has the backticks visible in posts

### ISSUE THREAD

**Issue by unixorn** [jpanther/congo#367]
### What happened?

When I write something like `config.toml` in a post in backticks, I expect config.toml to be in code style, without the backticks remaining visible.

Attached a screen shot from https://jpanther.github.io/congo/docs/configuration/

<img width="665" alt="Screen Shot 2022-11-13 at 8 22 56 AM" src="https://user-images.githubusercontent.com/23920/201529788-f71d4277-5d5e-4994-be42-8062acdbd215.png">

It's showing the correct code style, but the backticks are visible :-(

I'm doing these tests on macOS 12.6 and don't have a Windows machine to test there.

### Theme version

2.4.0

### Hugo version

hugo v0.105.0+extended

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by jpanther** [comment]
The backticks being visible is a design choice and not a bug. See https://github.com/jpanther/congo/issues/72 for details on how to adjust the behaviour.
