### ISSUE TITLE
Code highlight gets cut when scroll is available

### ISSUE THREAD

**Issue by cgutierr-zgz** [jpanther/congo#374]
### What happened?

When we use the highlight for a code snippet it gets cut off on the "overflowing scrolling part(?)"

I noticed this on Google chrome on my pixel 4a
![Screenshot_20221116-174823](https://user-images.githubusercontent.com/18635739/202243168-7fb74817-64d3-427d-a25f-84958bd02f77.png)

### Theme version

2.4.1

### Hugo version

0.15

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
Thanks for the report, @cgutierr-zgz. I'll have a look into this and see if I can make some adjustments.

**Comment by cgutierr-zgz** [comment]
I think the problem does persist it even seems a bit more aggressive now 

![Screenshot_20221122-094841](https://user-images.githubusercontent.com/18635739/203268411-03b32f9a-ea38-43a3-9152-9bae250377e5.png)
![Screenshot_20221122-094836](https://user-images.githubusercontent.com/18635739/203268425-48fc49f9-cc3a-41cf-93dc-2f85e7d123ba.png)

**Comment by jpanther** [comment]
Oh no! I tested this using Chrome too and had no issues, but unfortunately I don't have an Android phone to be able to test it on there directly. I take it you're using the `highlight` shortcode to insert the code block?

**Comment by cgutierr-zgz** [comment]
Yes, this is an example from a post i made:

```md
{{<highlight dart "hl_lines=12">}}
// ...
final carlosCubit = SettingsCubit('carlos');
final dimaCubit = SettingsCubit('dima');
// ...

class SettingsCubit extends HydratedCubit<Settings> {
  SettingsCubit(this._id) : super(const Settings(themeMode: ThemeMode.system));

  final String _id;

  @override
  String get id => _id;
  //... other methods
}
{{</highlight>}}
```

If there's anything i can test, lmk, btw it does happen on google chrome too

**Comment by cgutierr-zgz** [comment]
Example from my chrome on mac -> Version 106.0.5249.119 (Official Build) (arm64)

using iphone XR view
<img width="432" alt="Screenshot 2022-11-22 at 10 04 33" src="https://user-images.githubusercontent.com/18635739/203272063-fa277683-8783-4d7f-b1a3-b880285f22a8.png">
<img width="409" alt="Screenshot 2022-11-22 at 10 04 38" src="https://user-images.githubusercontent.com/18635739/203272071-a031dcce-68a9-45b2-99dd-c0cf8b605de4.png">

using galaxy s8+

<img width="321" alt="Screenshot 2022-11-22 at 10 04 53" src="https://user-images.githubusercontent.com/18635739/203272097-3a469c7f-a6ca-495f-bc92-eb60b25a6e3d.png">
<img width="345" alt="Screenshot 2022-11-22 at 10 04 49" src="https://user-images.githubusercontent.com/18635739/203272101-bbe073bd-0555-46f3-8e31-9e2041deb7c1.png">


Chrome without any emulator view

<img width="543" alt="Screenshot 2022-11-22 at 10 07 36" src="https://user-images.githubusercontent.com/18635739/203272529-192cf02d-7e93-4203-a6f1-e44b3c38e885.png">

**Comment by jpanther** [comment]
So it looks like there was some CSS caching going on in my Chrome and I've now been able to replicate this! Looking into it again now.

**Comment by jpanther** [comment]
I've created #383 so that you can have a look and see if this fixes your issue. I've tested it in Chrome and it appears to be working now. Feel free to use the deploy preview on the PR on your device and let me know if the problem has been resolved.

**Comment by cgutierr-zgz** [comment]
Thanks @jpanther , it does look good now!
