### ISSUE TITLE
`meta name=description` not set from article description (or summary)

### ISSUE THREAD

**Issue by glennr** [jpanther/congo#377]
### What happened?

Hi!

I noticed the lighthouse SEO scores aren't 100% if you don't configure a (Site-wide).

> Document does not have a meta description
> Meta descriptions may be included in search results to concisely summarize page content. [Learn more](https://web.dev/meta-description/?utm_source=lighthouse&utm_medium=lr).

```toml
# config/_default/languages.en.toml
title = "My Blog"
# description = "blah"
```

Uncommenting the above appears to set the `<meta name="description" content="blah">` to be the same for all pages. This is not advisable, according to [this article](https://www.searchenginejournal.com/matt-cutts-answers-every-page-needs-unique-meta-description/78133/)

For the lazy, like me, inserting the  [.Page.Summary](https://gohugo.io/variables/page/). Which it appears is what the internal [OpenGraph](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html) template does. In fact, you can see this already working on each article page with `<meta name="og:description" content="the summary">`

Inspecting the variables that the [internal template for og:description](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html), I see

```html
# layouts/partials/extend-head.html
<meta name="description"
  content="{{ with .Description }}{{ . }}{{ else }}{{if .IsPage}}{{ .Summary }}{{ else }}{{ with .Site.Params.description }}{{ . }}{{ end }}{{ end }}{{ end }}" />
```

This defaults to the 
  1. optional frontmatter `description:` or
  2. the (autogenerated) Page Summary, or 
  3. the site config (assumes duplicate meta tags are better than nothing?)

But for meta tags to work the same way in Congo, I believe we would need this (breaking?) change:

```diff
  # layouts/partials/head.html
  {{ if templates.Exists "partials/extend-head.html" }}
-  {{ partialCached "extend-head.html" .Site }}
+  {{ partial "extend-head.html" . }}
  {{ end }}
```

I'm happy to send in an MR,  but wanted to discuss the preferred fix first.

### Theme version

2.0.5

### Hugo version

0.104.3

### What browsers are you seeing the problem on?

Firefox

**Comment by glennr** [comment]
Hold the phone. With that solution, the `meta` tag is rendered inside body on production builds (but fine in development ??!)

![image](https://user-images.githubusercontent.com/72130/202945472-a3f11eb8-e4bc-4017-87af-95e92c991627.png)

**Comment by jpanther** [comment]
Thanks for the issue report, @glennr. I agree that this is a valid issue and the proposed solution is a good design. It provides scope for a lot of customisation while adopting sensible defaults.

I don't think that this should be included in the `extend-head.html` partial though. That's intended to allow people to override the theme behaviour. It makes more sense to simply adjust the existing meta tag output within the `head.html` partial.

**Comment by glennr** [comment]
@jpanther thanks for the speedy reply. I've had a crack at it, based on your design ^
