### ISSUE TITLE
Small images added to posts are stretched beyond their native width, become pixilated. 

### ISSUE THREAD

**Issue by zebpalmer** [jpanther/congo#394]
### What happened?

Apologies if this is _works as intended_ or if you see it as a feature request (or I'm just totally missing something).

Smaller images (those smaller than a post's column width) are stretched and become very pixelated/hard to read. The workaround I see is to use `default=true`, which resets all the other styling making it inconsistent with the rest of the theme. The theme stretching an image beyond its native resolution seems like a bug to me. 

Related, and totally a feature request once (if) the above is fixed, it'd be nice to have a clean way to center an image that isn't large enough to be full width. I'm very much not a front-end person, but I found a hacky way to do it in custom css; that hack should probably never see the light of day. But handling this may be something to consider if the above is fixed. 

Thanks for the great theme; I'm starting to really like it. 

### Theme version

 v2.4.2

### Hugo version

v0.107.0+extended

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by zebpalmer** [comment]
Still an issue, shouldn't be marked stale yet.

**Comment by jpanther** [comment]
Thanks for the report, @zebpalmer. This is something that I think needs improvement as I agree that smaller images shouldn't be scaled to the article width. I'll have a look at some options. Apologies for the delayed response too, I've been super busy lately!

**Comment by zebpalmer** [comment]
Awesome! Thanks so much!
