### ISSUE TITLE
Layout shift on social icon hover in bio using Safari

### ISSUE THREAD

**Issue by Benjamin-Lee** [jpanther/congo#396]
### What happened?

When hovering over an icon in the author bio, the icon shifts location at the end of the transition. I don't see exactly what's causing this when looking at the classes.

https://user-images.githubusercontent.com/13618205/204908220-626f6f44-e9a2-47b4-87ca-7f036e17db8b.mov

This only happens when using Safari (tested on v16.1). No such issue on Chrome.

### Theme version

2.3.1

### Hugo version

v0.104.3+extended darwin/amd64

### What browsers are you seeing the problem on?

Safari

**Comment by jpanther** [comment]
Thanks for the report, @Benjamin-Lee. Apologies for my delayed response, I've been really busy. This looks like it's to do with how Safari hands off some CSS rendering to the GPU. I'll make some adjustments to make this look smoother.
