### ISSUE TITLE
featured/cover/thumb images not showing

### ISSUE THREAD

**Issue by gcailly** [jpanther/congo#409]
### Discussed in https://github.com/jpanther/congo/discussions/407

<div type='discussions-op-text'>

<sup>Originally posted by **hystedm** December  6, 2022</sup>
Trying to add 'featured' mages to my posts.

Using a page bundle technique have tried adding cover.jpg and thumb.jpg into directory of post but not arriving in render.  Have added a test image into post to check that is being pulled through.  Have looked at others sites and can't work out why it isn't working

Example post is: https://mark.hysted.com/back-to-the-commute/

Using cloudlfare via GitHub.</div>

**Comment by mackiser** [comment]
Having the same issue on my end

**Comment by ethanolivertroy** [comment]
I used featured.jpg and it works @gcailly

**Comment by gcailly** [comment]
`featured.jpg` ? The [doc](https://jpanther.github.io/congo/docs/getting-started/#feature-cover-and-thumbnail-images) mentions `feature.jpg` without "d". Could this be a problem with file naming ? I tried with adding the final "d" but no success.

Here is my folder :
![image](https://user-images.githubusercontent.com/109429289/207531880-398d6fbe-51ec-4655-afc4-e0cd24eaf86d.png)

**Comment by gcailly** [comment]
I found it.
I thought Congo module was automatically updated at build. But no : I had an older version of Congo...

```
hugo mod get -u
```

updated all modules and solved the problem.
It's in the Readme too.
