### ISSUE TITLE
Some images are rotated in site build vs. how they are on filesystem

### ISSUE THREAD

**Issue by alexjj** [jpanther/congo#421]
### What happened?

On a few of my [posts](https://alexjj.com/posts/2022/film-scanning-with-camera/), some images are rotated from their original orientation. On my filesystem they are all in the correct orientation.

I've tried rotating them and rebuilding the site but they remain in the same orientation. It's also a mix of portrait and landscape images.

[Github repo for that post.](https://github.com/alexjj/alexjj.com/tree/main/content/posts/2022/film-scanning-with-camera)

Any suggestions? Thanks.

### Theme version

v2.4.2

### Hugo version

v.0.108.0+extended

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Relevant Hugo log output

```shell
INFO 2022/12/19 22:21:51 syncing static files to /
LOG:   2022/12/19 22:21:51 Built in 112 ms
LOG:   2022/12/19 22:21:51 Watching for config changes in /home/alex/dev/alexjj.com/config/_default, /home/alex/dev/alexjj.com/config/_default/resources, /home/alex/dev/alexjj.com/config/_default/resources/_gen, /home/alex/dev/alexjj.com/config/_default/resources/_gen/assets, /home/alex/dev/alexjj.com/config/_default/resources/_gen/images, /home/alex/dev/alexjj.com/go.mod
```

**Comment by jpanther** [comment]
I'm not sure what would be causing this. The theme only uses standard Hugo image processing commands and so it shouldn't be rotating the images. I suspect this might be some sort of metadata issue in the images that is telling them to change orientation when Hugo is processing them.
