### ISSUE TITLE
custom css scheme not working after updating to v2.4.2

### ISSUE THREAD

**Issue by mackiser** [jpanther/congo#423]
### What happened?

custom css scheme not working after updating to v2.4.2

custom theme works when running `hugo server` locally on my machine, but once I push the code to the host service the site always defaults back to the Congo theme

I have the .css files located in the assets/css/schemes/ directory
![image](https://user-images.githubusercontent.com/2199450/208738083-8e287872-6c2f-4824-8f25-94e23a233a5f.png)

### Theme version

2.4.2

### Hugo version

v0.90.1-48907889

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by XdpCs** [comment]
I also have this problem.

**Comment by jpanther** [comment]
I suspect this might be related to the mixed case filename you're using. The theme outputs the URL to the stylesheet in lowercase and so depending on the filesystem you're hosting your site on, it may not find the file with the uppercase "B" in it.

**Comment by mackiser** [comment]
changed to all lowercase and it fixed my issue! Appreciate the help!
