### ISSUE TITLE
SharingLink URLs are Broken

### ISSUE THREAD

**Issue by larihuttunen** [jpanther/congo#431]
### What happened?

It seems that the URL parameters generated through sharingLinks buttons are not URLs, only file paths. In other words, the URL is missing the protocol + domain part when you click on a sharing button.

### Theme version

v2.4.2

### Hugo version

hugo v0.101.0+extended

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
Thanks for the report, @larihuttunen. I'm not seeing this issue when I build using the theme. Do you have an example repo where this issue is happening?

**Comment by larihuttunen** [comment]
Setting the baseURL helped also with this issue.

It might be good to add it to the default configuration, since based on the documentation I understood it was optional.

**Comment by jpanther** [comment]
Glad that helped! It's not in the default configuration because if you set it in certain deployments it will break. Since the parameter very much depends on your deployment scenario, it's usually best to set it using the build command via the command line.
