### ISSUE TITLE
Google Search Console Sitemap Errors

### ISSUE THREAD

**Issue by larihuttunen** [jpanther/congo#432]
### What happened?

* Submitting a sitemap.xml to the Google search console, I get the following errors:

![sitemap](https://user-images.githubusercontent.com/15632937/211028169-5b4dc3bd-23d1-4489-9af4-d5ab9c031e38.png)

* So it would seem that Google is expecting URLs there instead of relative paths?

### Theme version

v2.4.2

### Hugo version

hugo v0.101.0+extended

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
Thanks for the issue report, @larihuttunen. This looks like it could be an issue with the `baseURL`. Are you setting the parameter in your site configuration?

**Comment by larihuttunen** [comment]
As it turns our, no I was not. Setting it fixed this issue.

It might be good to add it to the default configuration, since based on the documentation I understood it was optional.

**Comment by jpanther** [comment]
Glad that helped! It's not in the default configuration because if you set it in certain deployments it will break. Since the parameter very much depends on your deployment scenario, it's usually best to set it using the build command via the command line.

**Comment by larihuttunen** [comment]
OK, thx.
