### ISSUE TITLE
Tag line height

### ISSUE THREAD

**Issue by lucamondini** [jpanther/congo#443]
### What happened?

On mobile, in case of long list of tags, the rectangles around them overlap.
<img width="296" alt="image" src="https://user-images.githubusercontent.com/59113589/212703210-bc7f0980-b39d-4044-8f34-90720626d4d5.png">
Setting line-height for .text-xs at > 1.35rem should help:
```
.text-xs {
    font-size: .75rem;
    line-height: 1.35rem;
}
```

### Theme version

2.4.2

### Hugo version

0.92.2

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by jpanther** [comment]
Thanks for the report @lucamondini, this fix will be included in the next release.
