### ISSUE TITLE
alignment when using hamburger menu

### ISSUE THREAD

**Issue by AntoineSoetewey** [jpanther/congo#445]
### What happened?

Thanks for v2.5.0 !

Just one question: is it normal that the text moves so much to the left when opening the hamburger menu?

See in this video:

https://user-images.githubusercontent.com/17910063/212926016-30e1d996-e35c-4342-9d04-28540ec1ac59.mov

Regards,
Antoine

### Theme version

v2.5.0

### Hugo version

v0.101.0

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by jpanther** [comment]
Oof, no. That is definitely a bug! Thanks for pointing it out. I suspect it's a result of the changes required to fix #399. Cross browser CSS is hard!
