### ISSUE TITLE
Extra space between link and dot

### ISSUE THREAD

**Issue by AntoineSoetewey** [jpanther/congo#453]
### What happened?

For some unknown reasons, a space is added between links and points:

![F94BB939-123D-4FBB-A389-353E9D883D85](https://user-images.githubusercontent.com/17910063/213968247-153a9a00-4cc1-4774-9b5c-37fe1b21e416.png)

The repo is available at: https://github.com/AntoineSoetewey/antoinesoetewey.com

### Theme version

v2.5.1

### Hugo version

v0.101.0

### What browsers are you seeing the problem on?

Chrome and Safari

**Comment by jpanther** [comment]
Thanks for picking this bug up, @AntoineSoetewey. This is actually a regression from the changes made in #446. I'll fix it up now.

**Comment by AntoineSoetewey** [comment]
Thanks @jpanther!
