### ISSUE TITLE
Unresponsive Navbar/Menu

### ISSUE THREAD

**Issue by okabrionz** [jpanther/congo#455]
### What happened?

it will be great if we have responsive navbar.

### Theme version

2.5.1

### Hugo version

v0.109.0

### What browsers are you seeing the problem on?

Chrome

### Relevant Hugo log output

```shell
none, it just come when i open on my small device
```

**Comment by jpanther** [comment]
Hey @okabrionz, the theme is fully responsive. What part of the navigation isn't working properly for you? Could you please provide more details - a sample repository or screenshots that depict the issue.
