### ISSUE TITLE
Menu is not closing for one-page site

### ISSUE THREAD

**Issue by AntoineSoetewey** [jpanther/congo#460]
### What happened?

Hello,

my website www.datanalyze.be is a one-page site in the sense that links in the menu redirects to a section of the home page.

I noticed that when I click on a link in the menu, it correctly redirects to the section but the menu stays open (and we have to click on the cross to close it).

See in practice: 

https://user-images.githubusercontent.com/17910063/215342929-5b8ce2e9-cbf0-4525-88e5-160316f08399.MOV

Would it be possible to implement the fact that the menu closes automatically after clicking on a link?

In case it helps, the repo is available at:

https://github.com/AntoineSoetewey/datanalyze

Thanks in advance!

### Theme version

v2.5.2

### Hugo version

v0.101.0

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by jpanther** [comment]
Thanks for raising this issue. I suppose this is an unusual one as this is kind of an edge case in the way the menu would normally be used. I agree that the UX for the way this works now is really not great, but I'm also not sure how best to address it.

If I were to make the menu close whenever a link is clicked, it will lead to the behaviour where the user will always see the menu dismiss even when navigating to another page and there'll be this delay where you see the original page content flash up before the browser navigates to the new link. And that seems like a worse outcome given that's how the majority of menu links would be used.

I have to do some thinking on how best to address this without adding a bunch of extra JavaScript that makes the site less performant.
