### ISSUE TITLE
cusdis comment system doesn't work

### ISSUE THREAD

**Issue by jmwyf** [jpanther/congo#477]
### What happened?

I add [cusdis](https://cusdis.com) `comments.html` in blog project layouts/partials/comments.html, but it doesn't work.
[blog code](https://github.com/jmwyf/jmwyf.github.io) is here.

### Theme version

latest 

### Hugo version

hugo v0.107.0+extended

**Comment by jpanther** [comment]
Thanks for the report. I'm interested to know why this isn't working. I'm not familiar with cusdis, but I had a quick look at the docs and couldn't see a reason why this wouldn't work. Do you get an error or some sort of output when you're trying to embed it in the page?

**Comment by jmwyf** [comment]
@jpanther no error and the output is normal, but the comment widget doesn't display.

**Comment by ghost** [comment]
Same issue here, can see that the comments.html gets processed as I have a h4 title which shows.  Can see that requests are made to cusdis.com in the waterfall diagram from gtmetrix so something is working but the actual form/comments don't show. Parameter ahowcomments set to true.

comments.Html:


      <h4>comments:</h4>
      <div id="cusdis_thread"
        data-host="https://cusdis.com"
        data-app-id="removed for privacy"
        data-page-id="{{ .File.UniqueID }}"
        data-page-url="{{ .Permalink }}"
        data-page-title="{{ .Title }}"></div>
      <script async defer src="https://cusdis.com/js/cusdis.es.js"></script>

**Comment by ghost** [comment]
Just tried removing the 'async defer' from last script line and is now working.  Tried leaving either async or defer and that caused comments to disappear.
