### ISSUE TITLE
File names are too long.

### ISSUE THREAD

**Issue by sidharthv96** [jpanther/congo#478]
### What happened?

The output CSS & JS filenames are too long when `SHA512` is used. 
This prevents deployment to Cloudflare as it fails when the 100-character limit is broken. 

I had to copy the head & vendor partial to my code and use `MD5` for now.

Would it be possible to add a config to choose which algorithm to use when fingerprinting? 

### Theme version

2.5.2

### Hugo version

v0.101.0

**Comment by jpanther** [comment]
Thanks for the report, I'll look to make this a configurable parameter so you can specify which hashing function is used for the fingerprinting.

**Comment by jpanther** [comment]
This is fixed in the next release with a new `fingerprintAlgorithm` theme parameter. The default hashing algorithm has also been changed to `sha256`.

**Comment by sidharthv96** [comment]
Thank you ❤️
