### ISSUE TITLE
Error: add site dependencies: load resources: loading translations: 

### ISSUE THREAD

**Issue by VZhuck** [jpanther/congo#503]
### Language

bn

### What's the issue?

Env: 
* linux, 
* hugo version: Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z

Steps to reproduce:
* hugo new site my-site
* cd my-site
* git init 
* git submodule add -b stable https://github.com/jpanther/congo.git themes/congo
* update config file with theme="congo"
* run: hugo 
* hugo generate Error (see below)
   PS. Please note that when I run the same steps on Windows I see no issues.

### Theme version

Stable & Dev

### Hugo version

0.68.3

### Relevant Hugo log output

```shell
Error: add site dependencies: load resources: loading translations: "/mnt/d/Repos/my-site/themes/congo/i18n/bn.yaml:1:1": failed to load translations: unable to parse translation #0 because invalid plural category externalurl_title
map[id:list translation:map[externalurl_title:অন্য ওয়েবসাইটের লিংক no_articles:এখানে তালিকাভুক্ত করার মতো আপাতত কিছুই নেই।]]
```

**Comment by jpanther** [comment]
Thanks for the report. The fact that this is working on Windows but not on Linux suggests to me that it has something to do with the file encoding. I'll make a change that hopefully rectifies this for you and will include it in the next update.

**Comment by kpspu** [comment]
Not sure, looks like the connected issue?
I've got this error in the attempt to install using Hugo:
```
hugo server
go: finding github.com/jpanther/congo/v2 v2.5.4
hugo: downloading modules …
go: finding github.com/jpanther/congo v1.6.4
go: downloading github.com/jpanther/congo/v2 v2.5.4
go: downloading github.com/jpanther/congo v1.6.4
go: extracting github.com/jpanther/congo v1.6.4
go: extracting github.com/jpanther/congo/v2 v2.5.4
hugo: collected modules in 4228 ms
Error: add site dependencies: load resources: loading translations: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/jpanther/congo/v2@v2.5.4/i18n/bn.yaml:1:1": failed to load translations: unable to parse translation #0 because invalid plural category copied
map[id:code translation:map[copied:কপি হয়ে গেছে copy:কপি করুন]]
```
