### ISSUE TITLE
Author Image file cropped

### ISSUE THREAD

**Issue by mchlebosz** [jpanther/congo#526]
### What happened?

When Using `author.image` the image seems to be cropped, then rounded. It is not css as the image provided is already cropped. 
Everything done accoring to instructions
```
/assets/ 
| ---- img/  
       | -- problem.jpg  
```
`  image = "img/problem.jpg"`

Input image:
![problem](https://user-images.githubusercontent.com/33816049/230498664-dfb5f083-61d4-48eb-b643-792234f1d9d3.jpg)
Page:
![image](https://user-images.githubusercontent.com/33816049/230498737-b81b9004-808b-47aa-9a61-bac685bcf4aa.png)
Element:
![image](https://user-images.githubusercontent.com/33816049/230498940-295d0e99-10eb-478a-b955-cdc04e99e52c.png)
Hugo shows no errors 

### Theme version

v2.5.3

### Hugo version

v0.111.3+extended windows/amd64

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

**Comment by mchlebosz** [comment]
The problem seems to be in Smart Crop in `layouts/partials/home/profile.html` in header 
Line: 8
![image](https://user-images.githubusercontent.com/33816049/230503583-579b4197-47e8-453f-824d-e6f60bd2a6b4.png)
[https://gohugo.io/content-management/image-processing/#anchor](url)

It wants to determine crop box on its own, sometimes cropping already perfectly sized images.

I see two solutions here:
1. You could change the `$authorImage.Fill "288x288"` to `$authorImage.Fit "288x288"` to remove the problem, but then when the image is not 1:1 it will be squished 
![image](https://user-images.githubusercontent.com/33816049/230504463-8f8ce379-09ca-4883-ae03-66d1d05c81f1.png)

2. You could change the `$authorImage.Fill "288x288"` to `$authorImage.Fit "288x288 Center"` then image will be cropped based on center of image 
![image](https://user-images.githubusercontent.com/33816049/230504918-de7ab382-4b32-4247-8367-3857b550e263.png)
In case of 1:1 image it is ok, otherwise we don't really know what crop box location user of theme prefers, so maybe it should be configurable or at least mentioned in docs. 
Here it is center:
![image](https://user-images.githubusercontent.com/33816049/230504703-7a92e4ce-716c-446e-8639-7430a35dc3a4.png)
Bottom Left:
![image](https://user-images.githubusercontent.com/33816049/230505176-9ce3a11f-c103-447f-93ac-8ee63cb5cdd9.png)



The above applies also to `layouts/partials/author.html`

**Comment by mchlebosz** [comment]
I suggest the second option #527

**Comment by metbril** [comment]
Keep?
