### ISSUE TITLE
"error calling partial" and "can't evaluate field Site in type *page.siteWrapper"

### ISSUE THREAD

**Issue by tomleary** [jpanther/congo#560]
### What happened?

I'm not exactly sure if this is an issue with the theme or Hugo itself, but I've searched for similar issues all over and couldn't find anything. I just updated everything to bring it in line with the new version of Hugo, but the `hugo` command throws up these incredibly dense and confusing errors.

I'm not sure what it's even trying to tell me, so I don't know what question to ask. Something about partials? I looked at the warnings.html file, but it didn't have much to tell me: 
<img width="1060" alt="Screenshot 2023-05-23 at 8 26 04 PM" src="https://github.com/jpanther/congo/assets/82277734/3f4f4916-b28d-4b02-bf18-1daa0956d52f">

I checked out the files listed, but can't tell what's wrong with them at a glance.

Any help would be appreciated. Thanks.

### Theme version

v2?

### Hugo version

v0.112.1+extended darwin/arm64

### Relevant Hugo log output

```shell
❯ hugo
Start building sites … 
hugo v0.112.1+extended darwin/arm64 BuildDate=unknown
ERROR 2023/05/23 20:18:02 render of "page" failed: "/Users/_/_/themes/congo/layouts/_default/baseof.html:1:4": execute of template failed: template: _default/single.html:1:4: executing "_default/single.html" at <partial "partials/functions/warnings.html" .Site>: error calling partial: "/Users/_/_/themes/congo/layouts/partials/functions/warnings.html:1:14": execute of template failed: template: partials/functions/warnings.html:1:14: executing "partials/functions/warnings.html" at <.Site.Params.showAppearanceSwitcher>: can't evaluate field Site in type *page.siteWrapper
ERROR 2023/05/23 20:18:02 render of "section" failed: "/Users/_/_/themes/congo/layouts/_default/baseof.html:1:4": execute of template failed: template: _default/list.html:1:4: executing "_default/list.html" at <partial "partials/functions/warnings.html" .Site>: error calling partial: "/Users/_/_/themes/congo/layouts/partials/functions/warnings.html:1:14": execute of template failed: template: partials/functions/warnings.html:1:14: executing "partials/functions/warnings.html" at <.Site.Params.showAppearanceSwitcher>: can't evaluate field Site in type *page.siteWrapper
ERROR 2023/05/23 20:18:02 render of "taxonomy" failed: "/Users/_/_/themes/congo/layouts/_default/baseof.html:1:4": execute of template failed: template: _default/taxonomy.html:1:4: executing "_default/taxonomy.html" at <partial "partials/functions/warnings.html" .Site>: error calling partial: "/Users/_/_/themes/congo/layouts/partials/functions/warnings.html:1:14": execute of template failed: template: partials/functions/warnings.html:1:14: executing "partials/functions/warnings.html" at <.Site.Params.showAppearanceSwitcher>: can't evaluate field Site in type *page.siteWrapper
ERROR 2023/05/23 20:18:02 render of "home" failed: "/Users/_/_/themes/congo/layouts/_default/baseof.html:1:4": execute of template failed: template: index.html:1:4: executing "index.html" at <partial "partials/functions/warnings.html" .Site>: error calling partial: "/Users/_/_/themes/congo/layouts/partials/functions/warnings.html:1:14": execute of template failed: template: partials/functions/warnings.html:1:14: executing "partials/functions/warnings.html" at <.Site.Params.showAppearanceSwitcher>: can't evaluate field Site in type *page.siteWrapper
Total in 33 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/Users/_/_/themes/congo/layouts/_default/baseof.html:1:4": execute of template failed: template: _default/single.html:1:4: executing "_default/single.html" at <partial "partials/functions/warnings.html" .Site>: error calling partial: "/Users/_/_/themes/congo/layouts/partials/functions/warnings.html:1:14": execute of template failed: template: partials/functions/warnings.html:1:14: executing "partials/functions/warnings.html" at <.Site.Params.showAppearanceSwitcher>: can't evaluate field Site in type *page.siteWrapper
```

**Comment by jpanther** [comment]
Looks like this is a result of the new combined config changes that were introduced in Hugo 0.112.0.

**Comment by BenAlexanderAU** [comment]
This fix may have introduced a bug in multilingual sites in pre and post 0.112 hugo.

## Summary 

When a multiple languages are enabled, the ``displayName`` shows the current language name/icon (twice).
The links are correct, and when clicking on the second language, both ``displayName`` name/icon switches to this name/icon (twice)

### Expected behaviour:

When multiple languages are enabled, the ``displayName`` should display both language options, eg:

> EN | DE (linking to ***.com and ***.de)

### Actual behaviour:

When multiple languages are enabled, the ``displayName`` actually displays both language options with the same name, eg:

> EN | EN (linking to ***.com and ***.de)

Clicking on the second EN option here, goes to the correct DE URL, and now both names are DE.

> DE | DE (linking to ***.com and ***.de)

---

While you are looking at this, can I add a **feature request**?

Rather than displaying both (or all) language names, can it either:

- Display a single drop down icon, to toggle between available languages
- If only two languages are available, display the non-active ``displayName`` to toggle between them.

This may make the header look a little less cluttered for some websites :)

Thanks for your awesome work!

**Comment by kevinlinxc** [comment]
I get this error in analytics.html as well when building to production:

https://github.com/jpanther/congo/blob/3dd7fe455dc40dbbb09f3670ba4e1bd51395bf5c/layouts/partials/analytics.html#L2

Was this missed?

I tried bandaid fixing this by overriding analytics.html, but the _internal/google_analytics.html also seems to use .Site.: https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/google_analytics.html#L1

Is there any possible fix for this?

**Comment by kevinlinxc** [comment]
I resolved this - needed to keep my head.html up to date https://github.com/gohugoio/hugo/issues/11160
