### ISSUE TITLE
`copyright` in the language configuration does not apply

### ISSUE THREAD

**Issue by sorairolake** [jpanther/congo#572]
### What happened?

Even if [`copyright`](https://jpanther.github.io/congo/docs/configuration/#configuration) is set, it is not applied and the default value is applied. At least as of Hugo v0.110.0, this works as expected.

### Theme version

v2.6.0

### Hugo version

v0.112.3+extended

### What browsers are you seeing the problem on?

Firefox

**Comment by jpanther** [comment]
Thanks for the report. This is a result of changes in Hugo v0.112.0 and will be fixed in the next theme release.
