### ISSUE TITLE
Version 2.6.0 squishes my main menu together

### ISSUE THREAD

**Issue by kevinlinxc** [jpanther/congo#589]
### What happened?

After updating to version 2.6.0, (2.5.4 does not have this problem), my main menu items are squished together:
<img width="387" alt="image" src="https://github.com/jpanther/congo/assets/44324811/9b4fb964-8877-4bd6-afcf-5fbe57fdd8d2">

### Theme version

2.6.0

### Hugo version

v0.114.1

### What browsers are you seeing the problem on?

Firefox

**Comment by kevinlinxc** [comment]
Figured it out - I was overriding `basic.html`, needed to update it with the tailwind css tags from 2.6.0's basic.html

**Comment by rtwld** [comment]
I've got the same issue. After upgrading to congo v2.8.2 (using Hugo v0.125.3 and Safari v17.4.1), I get:

<img width="400" alt="image" src="https://github.com/jpanther/congo/assets/7947266/a6b2df7e-f0b1-4463-83d2-f3c45282c28a">

However, I don't think am overriding `basic.html` like @kevinlinxc, at least not intentionally. Any suggestion how to troubleshoot this?
