### ISSUE TITLE
Images showing low resolutions

### ISSUE THREAD

**Issue by TikkunCreation** [jpanther/congo#601]
### Issue description

I'm not quite sure that this is a bug, but it might be.

Images in my project look high quality when I view them on my computer, but on my congo site, they look low quality, despite being shown smaller.

Is this a bug, or am I making a simple mistake in the way I'm using images? I wonder if it's a CSS issue. I don't have any custom CSS on my site.

### Theme version

v2.6.1

### Hugo version

hugo v0.115.0+extended darwin/arm64 BuildDate=unknown

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.)

**Comment by DejavuMoe** [comment]
It's not a bug in the theme, Congo resizes and splits the site's images into multiple sizes by default, see [render-image.html](https://github.com/jpanther/congo/blob/dev/layouts/_default/_markup/render-image.html#L28-L41).

If we pre-process the image quality manually (compressing or converting the format) and we don't want Congo to process the images for us, in the root directory of our Hugo project we can create a new file `layouts/_default/_markup/render-image.html` , and set the format in which you don't want Congo to process the image, for example:

```html
{{ $url := urls.Parse .Destination }}
{{ $altText := .Text }}
{{ $caption := .Title }}
{{ $lazyLoad := $.Page.Site.Params.enableImageLazyLoading | default true }}
{{ if findRE "^https?" $url.Scheme }}
  <figure>
    <img
      class="mx-auto my-0 rounded-md"
      src="{{ $url.String }}"
      alt="{{ $altText }}" 
      {{ if $lazyLoad }}
        loading="lazy"
      {{ end }}
    />
    {{ with $caption }}<figcaption class="text-center">{{ . | markdownify }}</figcaption>{{ end }}
  </figure>
{{ else }}
  {{ $resource := "" }}
  {{ if $.Page.Resources.GetMatch ($url.String) }}
    {{ $resource = $.Page.Resources.GetMatch ($url.String) }}
  {{ else if resources.GetMatch ($url.String) }}
    {{ $resource = resources.Get ($url.String) }}
  {{ end }}
  {{ with $resource }}
    <figure>
      <img
        class="mx-auto my-0 rounded-md"
        <!-- For example: in addition to SVG, we also want images in WebP format and GIF format not to be processed -->
        {{ if or (eq .MediaType.SubType "svg") (eq .MediaType.SubType "webp") (eq .MediaType.SubType "gif") }}
          src="{{ .RelPermalink }}"
        {{ else }}
          {{ if lt .Width 660 }}
            src="{{ .RelPermalink }}"
          {{ else }}
            srcset="
            {{- (.Resize "330x").RelPermalink }} 330w,
            {{- (.Resize "660x").RelPermalink }} 660w,
            {{- (.Resize "1024x").RelPermalink }} 1024w,
{{- (.Resize "1320x").RelPermalink }} 2x"
            src="{{ (.Resize "660x").RelPermalink }}"
          {{ end }}
        {{ end }}
alt="{{ $altText }}"
        {{ if $lazyLoad }}
          loading="lazy"
        {{ end }}
      />
      {{ with $caption }}<figcaption class="text-center">{{ . | markdownify }}</figcaption>{{ end }}
    </figure>
  {{ else }}
    <figure>
      <img
        class="mx-auto my-0 rounded-md"
        src="{{ $url.String }}"
        alt="{{ $altText }}"
        {{ if $lazyLoad }}
          loading="lazy"
        {{ end }}
      />
      {{ with $caption }}<figcaption class="text-center">{{ . | markdownify }}</figcaption>{{ end }}
    </figure>
  {{ end }}
{{ end }}
```

I'm not sure if this is the perfect way to work, but it worked for the pictures in my posts.

**Comment by TikkunCreation** [comment]
@DejavuMoe Good to know, I'll give that a try when I see the issue next - thank you!

**Comment by TikkunCreation** [comment]
Closing, planning to use @DejavuMoe's fix

**Comment by TikkunCreation** [comment]
That solved it, thanks @DejavuMoe

**Comment by bhumish** [comment]
I tried the above, but not working in my case. I made the same file in my base Hugo folder, and changed it in the congo theme's layout folder also.
