### ISSUE TITLE
Katex is broken in v2.6.1

### ISSUE THREAD

**Issue by kevinlinxc** [jpanther/congo#603]
### Issue description

With this in my go.mod:
```
module github.com/kevinlinxc/stemformulas.com

go 1.20

require github.com/jpanther/congo/v2 v2.6.1 // indirect
```
When I run hugo server, I get `failed to extract shortcode: template for shortcode "katex" not found`

Downgrading to 2.6.0 fixes the problem.

### Theme version

v2.6.1

### Hugo version

v0.144.1+extended

**Comment by jukremer** [comment]
I have the same issue with `button` and `lead`.

**Comment by kevinlinxc** [comment]
I had this problem with 2.6.0 today, upgrading to 2.6.1 fixed it. This leads me to believe it's not version dependent, but something else.

**Comment by jukremer** [comment]
After `hugo mod get -u` I noticed Hugo tried to download Congo v1.6.? 

A restart of my system fixed the issue for me.

**Comment by jpanther** [comment]
Is this still an issue? The `katex` template is basically empty and is only used to tell the theme to include the necessary scripts.

**Comment by kevinlinxc** [comment]
Transient issue, I guess we can assume it's not a bug until someone can reliably reproduce it

**Comment by jpanther** [comment]
Since there hasn't been any further discussion on this issue, and Congo v2.7.0 contains a number of updates to KaTeX, I'm going to close this for now. If you see any new problems in the latest release, feel free to create a new issue.
