### ISSUE TITLE
Clicking on table of contents link doesn't fully scroll to that section header

### ISSUE THREAD

**Issue by TikkunCreation** [jpanther/congo#621]
### Issue description

To reproduce, have a very very long post. Then, click on a section header in the table of contents (or a manual section link added in the post). It'll scroll part way but not all the way. Repeated clicking on the section header will eventually take it to the right header. Expected behavior is that it'd scroll all the way on the first click.

Reproduced on Chrome and Safari

### Theme version

v2.6.1

### Hugo version

v0.115

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.), WebKit (Safari)

**Comment by TikkunCreation** [comment]
Could someone please see if they can reproduce this issue?

**Comment by jpanther** [comment]
Do any of the pages in the example site exhibit this issue? I can't reproduce it but I'm not sure how long "very, very long" is. Do you have an example you could share?

**Comment by TikkunCreation** [comment]
They don't. I suspect it'll show with 10,000 words of lorem ipsum with 4-5 levels (h2 -> h6) of depth in some places
