### ISSUE TITLE
"Failed to render shortcode "figure"

### ISSUE THREAD

**Issue by dr460nf1r3** [jpanther/congo#64]
### What happened?

I'm trying to insert a picture into [this file](https://github.com/dr460nf1r3/website/blob/main/content/projects/chaotic-aur.md) as follows:

`{{< figure src="chaotic-compilation.png" >}}`

Expected behaviour: `hugo server` succeeds.
Actual behaviour: An error message is shown as follows: (happens with both stable/-git hugo)
```
Start building sites …
hugo v0.92.0-DEV+extended linux/amd64 BuildDate=unknown
Error: Error building site: "/home/nico/Documents/misc/website/content/projects/chaotic-aur.md:19:1": failed to render shortcode "figure": failed to process shortcode: "/home/nico/Documents/misc/website/themes/congo/layouts/shortcodes/figure.html:7:21": execute of template failed: template: shortcodes/figure.html:7:21: executing "shortcodes/figure.html" at <$image.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
Built in 68 ms
```

### Theme version

Latest

### Hugo version

 v0.92.0-DEV

### Relevant Hugo log output

```shell
Start building sites …
hugo v0.92.0-DEV+extended linux/amd64 BuildDate=unknown
Error: Error building site: "/home/nico/Documents/misc/website/content/projects/chaotic-aur.md:19:1": failed to render shortcode "figure": failed to process shortcode: "/home/nico/Documents/misc/website/themes/congo/layouts/shortcodes/figure.html:7:21": execute of template failed: template: shortcodes/figure.html:7:21: executing "shortcodes/figure.html" at <$image.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
Built in 68 ms
```

**Comment by jpanther** [comment]
Interesting... where is the image file located? The shortcode uses [Hugo page bundles](https://gohugo.io/content-management/page-resources/) and so it expects the image to be a resource that is associated with the content that you are using it in.

**Comment by dr460nf1r3** [comment]
Oh well. The page bundle page was enlightening. I did not create a sub-folder for the different project pages. After doing so and renaming the pages to index.md it worked flawlessly.

**Comment by rshmhrj** [comment]
Hi @jpanther -- I ran into this issue just now as well.  Can we add a blurb on the [shortcodes doc page](https://jpanther.github.io/congo/docs/shortcodes/) explaining the usage of `figure` and `screenshot`?

If you think this makes sense, I can give it a shot.

**Comment by davidolrik** [comment]
I also ran into this problem with images located in `/static` which are not "resources".

The shortcode that this overrides does not mention this limitation.

**Comment by resoltico** [comment]
Hello,

I would like to render a figure in _layouts/partials/home/custom.html_
` {{< figure src="image.svg" >}}`

The image is located in the _assets/_

But, when building, I am getting an error:
`parse failed: template: partials/home/custom.html:16: unexpected "<" in command`

May I have a suggestion how to fix this, please.
Thank you!
