### ISSUE TITLE
GitHub Pages Fails to Deploy

### ISSUE THREAD

**Issue by mdrxy** [jpanther/congo#653]
### Issue description

Attempting to run the supplied documentation GitHub Pages deploy action will fail by default. 

I had to change these settings under the repository's Settings-Action-General.

- **Workflow Permissions:** Read and Write

- **Check:** Allow GitHub Actions to approve pull requests

### Theme version

2.6.1

### Hugo version

hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended darwin/arm64 BuildDate=2023-08-31T11:23:51Z VendorInfo=brew

**Comment by jpanther** [comment]
Thanks for this report, I'll update the deployment docs to include this information.
