### ISSUE TITLE
Cannot access page context when using extend-head feature

### ISSUE THREAD

**Issue by micah-svenson** [jpanther/congo#657]
### Issue description

I am incorporating plotly.js graphs into my website, which requires a couple of additional `<script>` tags in the `<head>` of the document. 

I found the congo theme feature that allows extending congo's `head.html` partial via the `extend-head.html` file. Perfect! 
However, I also want to add a piece of front matter config to an individual page such that the additional scripts are only loaded on pages that need it (when `plotly: true` is specified in the front matter of a given page). This functionality requires the following code to be placed in `extend-head.html`
```html
{{ if .Params.plotly }}
<script src="https://d3js.org/d3.v7.min.js"></script>
<script src="https://cdn.plot.ly/plotly-2.11.1.min.js"></script>
{{ end }}
```

When I build the site, the plots won't render, but there are no errors. If I remove the conditional logic, then the plots do render, but the scripts are included in all pages including ones that don't need them.

After some digging, I found that when congos `head.html` partial calls the `extend-head.html` partial, it passes `.Site` as the context, which prevents accessing the page front matter. The issue is fixed when I instead pass `.` as the context to `extend-head.html`.

I am opening this as an issue because I think it's a bug, but I can't rule out the possibility of there being other considerations for passing `.Site` as context. I will note that the sibling partial `extend-footer.html` does pass the full `.` context when called.

### Example

[code](https://github.com/micah-svenson/congo/tree/bug-repro)

To run the example:
1. clone branch and build example site with `npm run example`
```
git clone --branch bug-repro --single-branch https://github.com/micah-svenson/congo.git
```
2. navigate to `http://localhost:8008/congo/samples/plotly/`

The plot won't render until you change the context of the `extend-head.html` call from `.Site` to `.` as the post mentions.
<img width="970" alt="image" src="https://github.com/jpanther/congo/assets/38704799/7afd4751-d9db-4fb3-b5c3-c94681086f0c">

### Theme version

2.6.1

### Hugo version

hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended darwin/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=brew

### Which browser rendering engines are you seeing the problem on?

WebKit (Safari)

### URL to sample repository or website

https://github.com/micah-svenson/congo/tree/bug-repro

**Comment by jpanther** [comment]
Thanks for the issue report. This isn't actually a bug as the use of `.Site` is intended, however I can see why this is an issue for your use case. The reason it uses the site variable is for performance reasons so that it can cache the partial when the site is built, as normally scripts and things that would be included here would be required site-wide. I have had others report this issue in the past and so I'm open to changing the behaviour as the performance gains are negligible for most sites.

The other option you have to solve your use case is to create a shortcode partial for your plotly graphs so that the required scripts are only included on pages that need them.

**Comment by micah-svenson** [comment]
Ok, that makes sense. Thanks for the response!

I looked into using a shortcode for the plotly graphs, but the issue I am having there is that the resource script tag is included multiple times on single page if you have more than one plot, which will be a common use case for me. I definitely may be missing something obvious but I couldn't find a way to omit the script tags if a plotly partial had already been included in the current page.
 I did a little profiling, and though the scripts are only fetched 1x each, they are executed once for each plot they are included with. This adds 50-100 ms per plot to initial page load , which added up to a ~1 second delay in load time for 5 plots. The code for the plotly partial is included below for context.
```html
{{ $json := .Get "json" }}
{{ $height := .Get "height" | default "200px" }}
{{ $id := .Get "id" }}

<script src="https://d3js.org/d3.v7.min.js"></script>
<script src="https://cdn.plot.ly/plotly-2.11.1.min.js"></script>
<div id="{{$id}}" class="plotly" style="height:{{$height}};"></div>
<script>
  d3.json({{ $json }}).then(function (fig) {
      Plotly.newPlot('{{$id}}', fig.data, fig.layout, { responsive: true });
  });
</script>
```

If there isn't a solution to creating an isolated partial without performance hits, then I think it could make sense to update the behavior of extend-head. My impression of extend-head was that it allows the user the ability to add arbitrary customizations to the head of the document. It is also the natural place I was looking to add the plotly scripts. I think updating the partial to accept all context would be more flexible and intuitive for users of the theme and would afford an end user more control over customization without direct changes to the theme. It would also behave the same way as extend-footer, which I think would be better from a consistency and usability perspective.

If on the other hand the performance penalty of making this change is too great, then I think it would at least be worth adding some documentation that declares that as expected behavior. I would be happy to submit a PR for any of the above.

**Comment by jpanther** [comment]
Thanks for the extra detail here. I've decided it no longer makes sense to cache the extended head partial as it is just stunting flexibility for no reason. A while back the extended footer partial had the same issue and I removed `.Site` from there and so it makes little sense to have two different behaviours for the same feature. I'll merge your PR in and that should resolve this issue for you.

**Comment by micah-svenson** [comment]
Awesome, thank you!
