### ISSUE TITLE
Language switcher not working

### ISSUE THREAD

**Issue by AntoineSoetewey** [jpanther/congo#675]
### Issue description

Hello,

Thanks for the release of v2.7.0!

Following this new version, I have:

- updated [languages.en.toml](https://github.com/AntoineSoetewey/antoinesoetewey.com/blob/master/config/_default/languages.en.toml) and [languages.fr.toml](https://github.com/AntoineSoetewey/antoinesoetewey.com/blob/master/config/_default/languages.fr.toml) as mentioned in the release page.
- added the language switcher in [menu.en.toml](https://github.com/AntoineSoetewey/antoinesoetewey.com/blob/master/config/_default/menus.en.toml) and [menu.fr.toml](https://github.com/AntoineSoetewey/antoinesoetewey.com/blob/master/config/_default/menus.fr.toml)

The language switcher is displayed correctly, but the button does not seem to work:

https://github.com/jpanther/congo/assets/17910063/230e754c-af19-4320-abdf-bddb94976b07

Am I missing something?

### Theme version

v2.7.0

### Hugo version

0.119.0

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.)

### URL to sample repository or website

https://github.com/AntoineSoetewey/antoinesoetewey.com

**Comment by jpanther** [comment]
Thanks for the screen recording. Do you also have this issue when you view the example site?

https://jpanther.github.io/congo/

**Comment by AntoineSoetewey** [comment]
No, it works when viewing the example site.

**Comment by jpanther** [comment]
I've had a look at your repo and it seems like the `main.css` file is still using version 2.6.1. Do you need to do something in your build process to ensure these files are updated? I suspect the reason the menu is not appearing is because it needs some new css classes that are not present in the old version of the file.

**Comment by AntoineSoetewey** [comment]
There were indeed some old files in the assets folder in my root repository. After removing them, it works smoothly, thanks!
