### ISSUE TITLE
Getting 'Cannot read properties of null (reading 'setAttribute')' error in the console

### ISSUE THREAD

**Issue by Tanddant** [jpanther/congo#676]
### Issue description

I'm getting a JavaScript error on my page, seemingly related to setting the theme color 

Browser tried to call "e.setThemeColor", but e appears to be null

### Theme version

v2.7.0

### Hugo version

hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended windows/amd64

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.)

### URL to sample repository or website

https://blog.dan-toft.dk

**Comment by jpanther** [comment]
Thanks for the report, @Tanddant. I'm able to reproduce this and I'll get a fix out shortly.
