### ISSUE TITLE
Extra space after link

### ISSUE THREAD

**Issue by AntoineSoetewey** [jpanther/congo#679]
### Issue description

Hello,

there seems to be an extra space after a link and before a comma:

![IMG_4588](https://github.com/jpanther/congo/assets/17910063/9de4c6ce-d41c-453b-a7fc-bb391c1f0343)

This space shouldn’t be there based on my code: https://github.com/AntoineSoetewey/antoinesoetewey.com/blob/master/content/_index.md

### Theme version

v2.7.1

### Hugo version

0.119.0

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.)

### URL to sample repository or website

https://github.com/AntoineSoetewey/antoinesoetewey.com

**Comment by jpanther** [comment]
Ah thank you, I know exactly where this has come from - it's a side effect of whitespace in #655 padding the links. I'll get a fix out for this shortly.
