### ISSUE TITLE
Hugo 0.120.0 causes escaped HTML to appar around the reading time for each post

### ISSUE THREAD

**Issue by major** [jpanther/congo#689]
### Issue description

Escaped HTML suddenly appears near the "reading time" for each post with congo 2.7.2 and hugo 0.120.0:

```
<time datetime="2023-09-25 00:00:00 &#43;0000 UTC">25 September 2023</time><span class="px-2 text-primary-500">&middot;</span><span>1412 words</span><span class="px-2 text-primary-500">&middot;</span><span title="Reading time">7 mins</span>
```

### Theme version

v2.7.2

### Hugo version

hugo v0.120.0-20c3bae2c4839ec993ec3c353da4fd7b09215cd8+extended linux/amd64 BuildDate=2023-10-30T14:06:47Z VendorInfo=gohugoio

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.), Firefox (Mozilla Firefox)

### URL to sample repository or website

https://major.io/posts/

**Comment by major** [comment]
Example from the home page:
![image](https://github.com/jpanther/congo/assets/89910/d101af20-bc6e-428a-9d81-6892698becec)

And from a post itself:
![image](https://github.com/jpanther/congo/assets/89910/a11224d1-506f-4666-bb67-42aef8ad9ea7)

Blog source code: https://github.com/major/major.io

**Comment by jpanther** [comment]
Thanks for the report. Having just read the release notes for Hugo 0.120.0, I think I know why this is happening.

I'll aim to get a fix out shortly, but in the meantime, the best workaround is to build using Hugo 0.119.0.

**Comment by major** [comment]
Thank you, @jpanther!
