### ISSUE TITLE
Additional space added before links

### ISSUE THREAD

**Issue by tomasff** [jpanther/congo#695]
### Issue description

An empty space is being added before links when the character that precedes them is not a space.

<img width="57" alt="image" src="https://github.com/jpanther/congo/assets/15079464/cb459bc2-6641-4930-b75a-cd02f89e9c6d">

```
[[talk](http://www.youtube.com/)] [[slides](http://www.youtube.com/)]
 ```

Seems to be introduced as a result of #655

### Theme version

2.7.3

### Hugo version

hugo v0.120.3-a4892a07b41b7b3f1f143140ee4ec0a9a5cf3970+extended darwin/arm64 BuildDate=2023-11-01T17:57:00Z VendorInfo=brew

**Comment by jpanther** [comment]
Thanks for the report. I know exactly where this is coming from and I'll get a fix out for it shortly.
