### ISSUE TITLE
Are inline code blocks broken?

### ISSUE THREAD

**Issue by venteto** [jpanther/congo#72]
### What happened?

I was writing a paragraph which contained an *inline* code block using *single backticks* `like this one` and the color of the inlined text is changed while the backticks are still rendered, so it doesn't seem like it's working correctly.

![congo-inline-code](https://user-images.githubusercontent.com/7062385/147838769-2ccd9cce-118f-4a4c-8f66-d8bfe73b5e8f.png)

I was expecting something more like what GitHub does with the markdown in this issue (see "like this one" above), including hiding the backticks.

Inlined code blocks work as expected on another Hugo site I have that doesn't use any third-party theme.

### Theme version

v1.6.1

### Hugo version

hugo v0.89.4+extended linux/amd64 BuildDate=unknown (Manjaro)

### What browsers are you seeing the problem on?

Firefox

**Comment by jpanther** [comment]
Thanks for the report however this is not a bug as this is the correct theme behaviour. You could prevent this by using a `custom.css` file and overriding the `.prose code::before` and `.prose code::after` declarations and providing a new `content` value. The theme docs have more information on [overriding the stylesheet](https://jpanther.github.io/congo/docs/advanced-customisation/#overriding-the-stylesheet).

**Comment by laforcem** [comment]
It took me a while to figure out how to override this behavior and want to document it here for any future individuals who find this thread.

I put the following code in my `custom.css`:

```
.prose code::before {
    content: ''
}

.prose code::after {
    content: ''
}
```
