### ISSUE TITLE
function "page" not defined

### ISSUE THREAD

**Issue by ehussong** [jpanther/congo#724]
### Issue description

I'm attempting to build my first Hugo site using the Congo theme. Looks beautiful! When I run the instructions on the installation site I end up with an error though.

![Screenshot_20231126_222334](https://github.com/jpanther/congo/assets/6242748/eefe4612-8bd9-4daf-b854-b1fcce61fe1e)

### Theme version

v2.7.6

### Hugo version

hugo v0.101.0+extended linux/amd64 BuildDate=unknown

### Hugo output or build error messages

```bash
go: no module dependencies to download
go: added github.com/jpanther/congo/v2 v2.7.6
Error: add site dependencies: load resources: loading templates: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/jpanther/congo/v2@v2.7.6/layouts/partials/footer.html:7:1": parse failed: template: partials/footer.html:7: function "page" not defined
```

**Comment by ehussong** [comment]
If I follow the git install instructions I get a similar error.

`Error: add site dependencies: load resources: loading templates: "/home/<user>/Documents/hugo/<sitename>/themes/congo/layouts/partials/footer.html:7:1": parse failed: template: partials/footer.html:7: function "page" not defined
`

**Comment by jpanther** [comment]
This looks like you maybe haven't set up the theme configuration files. Your screenshot only takes you to step 4 of the instructions. Have you [followed this part (step 5)](https://jpanther.github.io/congo/docs/installation/#set-up-theme-configuration-files) of the installation docs?

**Comment by ehussong** [comment]
Interestingly enough, this morning it seems to be working fine. I have a suspicion that I was doing something funky with the Git config and switching folders that was causing it. I'm on a different machine today though as well so there's always a chance it is related to that. Either way, I appreciate your willingness to look at my issue so quickly and provide a response!
