### ISSUE TITLE
lead shordcode should render it's content as markdown formated text

### ISSUE THREAD

**Issue by slashformotion** [jpanther/congo#73]
### What happened?

I used the `lead` shortcode with markdown formated text and it didn't render

my input: 
```md
{{< lead >}}
The ***pbm*** package implements a Portable Bit Map (PBM) image decoder and encoder. The supported image color model is [color.RGBAModel](https://pkg.go.dev/image/color#RGBAModel).

The PBM specification is at http://netpbm.sourceforge.net/doc/pbm.html.
{{< /lead >}}
```

the result
![image](https://user-images.githubusercontent.com/45801817/147871556-274f267c-f11b-40ab-98a4-96284bff5605.png)

### Theme version

latest

### Hugo version

hugo v0.86.1-F6821B88 linux/amd64 BuildDate=2021-07-30T10:13:35Z VendorInfo=gohugoio

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by jpanther** [comment]
Thanks for reporting this. Definitely a bug! I'll fix it for the next release.
