### ISSUE TITLE
Table of content error in desktop and mobile view

### ISSUE THREAD

**Issue by chewstiltzoo** [jpanther/congo#794]
### Issue description

After the 2.8.0 upgrade I have noticed a bug in the table of contents (TOC).

In **desktop view**, the TOC was separated by a dashed line from the content up to 2.7.6. This line is no longer present.

Before (2.7.6):
<img width="993" alt="Screenshot 2024-01-23 at 14 34 31" src="https://github.com/jpanther/congo/assets/122687042/76096666-448d-40bb-8338-4fef1eaca796">

After (2.8.0):
<img width="975" alt="Screenshot 2024-01-23 at 14 34 16" src="https://github.com/jpanther/congo/assets/122687042/784f2378-1868-4677-b08c-c182185dd7a5">

In **mobile view**, the TOC had a solid line on the left as well as rounded corners on the left of its heading. Both are gone in 2.8.0. Furthermore in mobile view there was a significant reduction in white space between the page title and the TOC and a slight increase in white space below the TOC, which looks a bit off to me.

Before (2.7.6): 
<img width="306" alt="Screenshot 2024-01-23 at 14 36 59" src="https://github.com/jpanther/congo/assets/122687042/23bccadb-2741-4b44-8e94-7fb3b1f09d48">

After (2.8.0):
<img width="306" alt="Screenshot 2024-01-23 at 14 36 50" src="https://github.com/jpanther/congo/assets/122687042/eb4cd694-7245-4b20-965b-4cf4ceee9637">

I haven't tested if this is a language-specific bug (in my case German). Maybe this choice was deliberate; in this case I would be grateful for a config option to bring it back. Other than that, thank you very much for providing this amazing theme!

### Theme version

2.8.0

### Hugo version

hugo v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended darwin/arm64

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.)

**Comment by chewstiltzoo** [comment]
PS: Maybe unrelated, but I have noticed that cover images now overlap with the page title.

**Comment by jpanther** [comment]
Thanks for this report, this is definitely a bug. Will be fixed in the next release.
