### ISSUE TITLE
Background color inconsistent on mobile when dark mode enabled

### ISSUE THREAD

**Issue by nanowatts** [jpanther/congo#796]
### Issue description

Dark mode on mobile has a jarring break in background color. Verified in my[ personal usage of Congo](https://nanowatts.net) and in the[ official theme documentation](https://jpanther.github.io/congo/docs/advanced-customisation/). I have not been able to reproduce in any desktop browser and only see this issue in iOS Safari.
![IMG_3009](https://github.com/jpanther/congo/assets/949098/d03f8dbe-7012-4480-9169-d1289c8d9186)
![IMG_3010](https://github.com/jpanther/congo/assets/949098/37f3c3b0-df81-4f1c-b370-b6b0603d74cd)

### Theme version

2.4.2

### Hugo version

hugo v0.108.0+extended darwin/arm64

### Which browser rendering engines are you seeing the problem on?

WebKit (Safari)

### URL to sample repository or website

nanowatts.net

**Comment by wolfspyre** [comment]
Does this problem still manifest with current theme version and current hugo? 
(current hugo: 0.122)  (current congo 2.8.0)

(quite a few things that were impactful have changed since... so.... it's worth checking imo)

**Comment by pomeloy** [comment]
> Does this problem still manifest with current theme version and current hugo? (current hugo: 0.122) (current congo 2.8.0)

Yes.

For a quick and dirty solution add this to assets/js/appearance.js:
```
window.addEventListener("load", function(){
  setThemeColor();
});
```
