### ISSUE TITLE
Extra space after [ when using links

### ISSUE THREAD

**Issue by AntoineSoetewey** [jpanther/congo#811]
### Issue description

Hello,

As you can see on https://antoinesoetewey.com/research/ (in section "Preprints & submitted manuscripts"), there is an extra space between [ and working paper, such that it looks like [ working paper] instead of [working paper].

I checked the code (https://github.com/AntoineSoetewey/antoinesoetewey.com/blob/master/content/research.md?plain=1) and there is no extra space. So I guess it must be because I use a link in addition to [].

Is there a way to fix this?

Thanks in advance for your help!

Regards,
Antoine

### Theme version

v2.8.0

### Hugo version

Not sure

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.)

### URL to sample repository or website

https://github.com/AntoineSoetewey/antoinesoetewey.com

**Comment by Jh123x** [comment]
> ### Issue description
> Hello,
> 
> As you can see on https://antoinesoetewey.com/research/ (in section "Preprints & submitted manuscripts"), there is an extra space between [ and working paper, such that it looks like [ working paper] instead of [working paper].
> 
> I checked the code (https://github.com/AntoineSoetewey/antoinesoetewey.com/blob/master/content/research.md?plain=1) and there is no extra space. So I guess it must be because I use a link in addition to [].
> 
> Is there a way to fix this?
> 
> Thanks in advance for your help!
> 
> Regards, Antoine
> 
> ### Theme version
> v2.8.0
> 
> ### Hugo version
> Not sure
> 
> ### Which browser rendering engines are you seeing the problem on?
> Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.)
> 
> ### URL to sample repository or website
> https://github.com/AntoineSoetewey/antoinesoetewey.com
> 
> ### Hugo output or build error messages
> _No response_

You can do something like this instead

```md
[\[working paper\]](#link)
```

This will render to [\[working paper\]](#link)


Please let me know if there are any issues

EDIT:

I've tested it locally and it seems to work with this markdown
```markdown
[\[working paper\]](https://dial.uclouvain.be/pr/boreal/object/boreal:281061)
```
![image](https://github.com/jpanther/congo/assets/10459011/ab827f53-a035-441c-8f97-a640941f4225)

**Comment by AntoineSoetewey** [comment]
It works, thank you very much @Jh123x!
