### ISSUE TITLE
Author image does not render in profile homepage or author footer info

### ISSUE THREAD

**Issue by flexstrongo** [jpanther/congo#812]
### Issue description

Newly installed theme as a hugo submodule, copied relevant files out to config directories.  Every other change in the languages.en.toml file seems to take effect.  The author image never gets rendered anywhere it's supposed to.  I think the same is also happening for the header images.

Edit: the params.description also does not render under the profile set homepage

### Theme version

2.8.0

### Hugo version

0.123.1 extended

### Hugo output or build error messages

```bash
no build errors
```

**Comment by wolfspyre** [comment]
can you share the relevant config entries, and show the directory path you have the images stored in?

**Comment by flexstrongo** [comment]
Below is the languages.en.toml file.  The assets folder is in the root of my hugo folder, i.e: "siteFolder/assets".  But, this also fails with the out of the box img/author.jpg from the theme/examplesite setting. No errors come up when starting the hugo server.  I'd assume if the image path was wrong, it would bomb out with a missing file error or something.

```
languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Hugo Test"
copyright = "&copy; 2024"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["pages"]
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

[params.author]
  name = "Author"
  image = "assets/author.jpg"
  headline = "Some Headline"
  bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
  links = [
    { x-twitter = "https://twitter.com/" },
   # { facebook = "https://facebook.com/" },
   # { linkedin = "https://linkedin.com/" },
   # { youtube = "https://youtube.com/" },
  ]```

**Comment by flexstrongo** [comment]
OK.  I figured this out.  The documentation wasn't super clear, but the default is that the theme already assumes that "assets" is the root directory for the photo.  So, pointing just to "author.jpg" worked.

**Comment by flexstrongo** [comment]
Going to go ahead and close this

**Comment by wolfspyre** [comment]
> OK. I figured this out. The documentation wasn't super clear, but the default is that the theme already assumes that "assets" is the root directory for the photo. So, pointing just to "author.jpg" worked.

Sweet!
The `assets` folder is a hugo thing.

here's a couple links to the hugo discourse forum discussing assets / static dirs:
https://discourse.gohugo.io/t/difference-between-asset-and-static-folder/41203
https://discourse.gohugo.io/t/are-assets-and-static-folders-interchangeable/36778
