### ISSUE TITLE
Featured images overlapping with page title when article metadata hidden

### ISSUE THREAD

**Issue by chewstiltzoo** [jpanther/congo#827]
### Issue description

Since the 2.8.0 upgrade, cover images overlap with the page title in both desktop and mobile view. 

<img width="702" alt="Screenshot 2024-03-09 at 10 28 17" src="https://github.com/jpanther/congo/assets/122687042/f144cd5f-a442-4793-902a-278398c8e039">

On pages without cover images, the white space between the title and content is also substantially reduced compared to versions up to 2.7.6. Personally I preferred the previous amount of white space. If this is by design, I would greatly appreciate a config option for this.

Thanks a ton for your great work on this theme!

### Theme version

2.8.1

### Hugo version

hugo v0.123.7-312735366b20d64bd61bff8627f593749f86c964+extended darwin/arm64

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.)

**Comment by jpanther** [comment]
I'm not able to replicate this issue. Is there a certain configuration that causes it to happen?

**Comment by chewstiltzoo** [comment]
Not that I am aware of. I am on macOS and cannot test it on another OS right now. But it occurs on Chrome, Firefox and Safari, so it doesn't seem to be browser-specific. It also only happens for Congo v2.8.0 onwards, so it seems unrelated to the hugo version.

**Comment by jpanther** [comment]
Interesting, I'm using macOS and have tried on Firefox, Safari and Vivaldi and can't get it to happen.

The example site uses feature images... do you see the issue when you visit this page?
https://jpanther.github.io/congo/samples/emoji/

**Comment by chewstiltzoo** [comment]
No, I don't see it on that page. It also doesn't occur when I start a fresh Hugo project and copy the example site to the project root. 

I have diffed and double-checked all my config files with the defaults and might have come across the culprit: the problem stops occuring for me when I set `showDate = true` (just like in the example site, but unlike on my personal website). If relevant: other settings in `params.toml` where my site differs from the defaults are `autoSwitchAppearance`, `showTitle`, `layout`, `showAuthor`, `invertPagination`, `showReadingTime` and `showTableOfContents`. Thank you so much for looking into this.

**Comment by plimptm** [comment]
I've just had the same thing happen on a new site I'm putting together, and I believe it is only occurring when `showDate` is set to `false`.

When I tinkered with my browser's developer tools to effectively collapse the date field on the example site you linked, I was able to reproduce the issue:

![2024-04-27-224932_1781x776_scrot](https://github.com/jpanther/congo/assets/12819119/68752c30-1a20-47e1-aa22-14ab1ecb753c)

**Comment by jpanther** [comment]
Thanks, I'm able to replicate this when setting all the article metadata flags to false. Working on a fix now.

**Comment by plimptm** [comment]
> Thanks, I'm able to replicate this when setting all the article metadata flags to false. Working on a fix now.

Just tried out your fix and it did the trick. Thanks so much!

**Comment by jpanther** [comment]
Thanks, it will be in the next release. I'm aiming to publish later this week.
