### ISSUE TITLE
enableImageWebp breaks animated GIF files

### ISSUE THREAD

**Issue by major** [jpanther/congo#866]
### Issue description

If I enable `enableImageWebp`, it does a great job on all my images except for `.gif` files. It turns them into a static, non-animated image. If I set `enableImageWebp` to `false`, GIFs are animated again, but I lose the image optimizations on all of the other images.

Would it be possible to exclude `.gif` files from the optimization?

Thanks!

### Theme version

v2.8.2

### Hugo version

hugo v0.125.4-cc3574ef4f41fccbe88d9443ed066eb10867ada2+extended linux/amd64 BuildDate=2024-04-25T13:27:26Z VendorInfo=gohugoio

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.), Firefox (Mozilla Firefox)

### URL to sample repository or website

https://major.io

**Comment by jpanther** [comment]
Thanks for the report. I've been able to replicate this and will have a look at a fix.

**Comment by major** [comment]
Whoa, you are fast, @jpanther! 👏 I appreciate the fix!

**Comment by jpanther** [comment]
Thanks for the support; this one was an easy fix! Will aim to push it to stable in the next few days.
