### ISSUE TITLE
Unexpected blank line when using multiple lines in an alert box

### ISSUE THREAD

**Issue by kneep** [jpanther/congo#877]
### Issue description

single line:
<img width="656" alt="image" src="https://github.com/jpanther/congo/assets/525419/05cb500e-601a-40f8-b5a8-ec1368518598">
```
{{< alert >}}
abc
{{< /alert >}}
```

multiple line:
<img width="649" alt="image" src="https://github.com/jpanther/congo/assets/525419/d167356e-a32f-49e5-9988-6fd23507a5c4">
```
{{< alert >}}
abc

def
{{< /alert >}}
```

The first and last blank lines of the second box are unexpected. Not sure about the middle one.

### Theme version

v2.8.2

### Hugo version

hugo v0.125.7+extended darwin/arm64 BuildDate=2024-05-08T14:46:24Z VendorInfo=brew

### Which browser rendering engines are you seeing the problem on?

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, Opera, etc.), WebKit (Safari)

**Comment by Jh123x** [comment]
This seems to be due to the `markdownify` partial in the `alert` shortcode.

Below is an example without `markdownify` in the alert box. But not sure if it affect other items
![image](https://github.com/jpanther/congo/assets/10459011/dfdbe843-10da-4577-9a3d-db43299680e1)

**Comment by SebastianGrans** [comment]
I'm seeing this issue as well. Would be great if this could be opened again :)

**Comment by wolfspyre** [comment]
iirc jmooring has advocated for the use of renderString vs  markdownify; but i suspect this to be an artifact caused by prettier

**Comment by yash-garg** [comment]
did anyone figure out the fix for this?
