### ISSUE TITLE
CSS issue with short browser viewports

### ISSUE THREAD

**Issue by brafales** [jpanther/congo#93]
### What happened?

There seems to be an issue with the style of the site when the viewport of the browser is relatively short. The whole content div seems to move a few pixels left or right depending on the size of the viewport.

I have attached a small video showing how the style of the page changes depending on the browser viewport, the video is capturing the congo documentation site. I have also experienced this behaviour on my personal site, with the "profile" layout on the homepage.

Because this doesn't seem to happen on all layouts, sometimes when changing from one page to another as a user I notice how the new page is slightly misaligned with the previous one.

https://user-images.githubusercontent.com/521385/151129651-28492b45-6a8b-4bb8-8898-7fff97ed66b3.mov

.

### Theme version

1.6.4

### Hugo version

v0.91.2

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by jpanther** [comment]
Thanks for the report. I can't see the edge of the window in the video but isn't this simply because the browser is adding and removing the vertical scroll bar? I'm not sure this is any different to how most responsive websites behave when the viewport changes like this.

**Comment by brafales** [comment]
You're absolutely right, that's what's happening. Happy to close that, thanks for looking into it!
