### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by larihuttunen** [jpanther/congo#935]
### Issue description

I get a deprecation warning when running hugo server to develop a page locally.

### Theme version

v2.9.0

### Hugo version

hugo v0.134.2+extended openbsd/amd64 BuildDate=unknown

### Hugo output or build error messages

```bash
WARN  deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in a future release. Use hugo.IsMultilingual instead.
```

**Comment by jpanther** [comment]
Fixed in #921
