### ISSUE TITLE
assets/icons/bluesky.svg needs fill="currentColor"

### ISSUE THREAD

**Issue by ghost** [jpanther/congo#969]
### Issue description

Bluesky icon does not follow colour of other icons e.g. in author profile at bottom of single page.  Appears to be lacking fill="currentColor" inside svg file.

### Theme version

current

### Hugo version

hugo v0.139.3+extended+withdeploy darwin/arm64

### Which browser rendering engines are you seeing the problem on?

WebKit (Safari)

**Comment by jpanther** [comment]
Fixed in #955.
